import fs from 'fs/promises';
import { getLogger } from './logger';
import { ToolProfile } from './profile';

const INSTRUCTIONS_CACHE_TTL_MS = 15 * 60 * 1000; // 15 minutes

/**
 * Upper bound, in bytes, for the default instructions of any tool profile.
 *
 * Some clients copy the server instructions into every tool definition. Codex code mode, for
 * example, ships the whole catalog in a single IPC frame capped at 64 MiB, so the cost of this text
 * is roughly `(tool count + 1) * instructions size`. Keep the default instructions short and serve
 * detailed workflow rules through get_capability_guidance instead of embedding them here.
 */
export const DEFAULT_INSTRUCTIONS_MAX_BYTES = 8 * 1024;

const HOSTED_INTRO = [
  'This is the hosted Sanka MCP server used by packaged AI clients.',
  '',
  'Tool descriptions and input schemas are the source of truth for what each tool does. This text intentionally does not repeat the tool catalog; read the tool list from the client instead of expecting it here.',
  '',
  'Routing:',
  '- Call get_capability_guidance with a short summary of the user request plus optional provider, object_type, and operation hints before ambiguous or multi-step Sanka work, and before refusing a capability. It returns the workflow rules for the matching area: records and CRM, messaging, sales and billing, procurement and Sanka Buy, workflows and automation, people, migration and Developer Cloud, partners.',
  '- Prefer the dedicated tool that matches the live operation. Use query_records and aggregate_records for filtered or counted rows instead of paging through list_* tools.',
  '- Start from connect_sanka when protected tools report that the session is not connected, and read current_workspace before workspace-scoped mutations.',
];

const FULL_INTRO = [
  'This is the Sanka MCP server.',
  '',
  'Tool descriptions and input schemas are the source of truth for what each tool does. This text intentionally does not repeat the tool catalog; read the tool list from the client instead of expecting it here.',
  '',
  'Routing:',
  '- Call get_capability_guidance with a short summary of the user request plus optional provider, object_type, and operation hints before ambiguous or multi-step Sanka work, and before refusing a capability. It returns the workflow rules for the matching area: records and CRM, messaging, sales and billing, procurement and Sanka Buy, workflows and automation, people, migration and Developer Cloud, partners.',
  '- Prefer the dedicated tool that matches the live operation. Use query_records and aggregate_records for filtered or counted rows instead of paging through list_* tools.',
  '- Use search_docs to find the right Sanka SDK method or parameter shape, and execute only for SDK workflows that no dedicated tool covers.',
  '- Start from connect_sanka when protected tools report that the session is not connected, and read current_workspace before workspace-scoped mutations.',
];

const SHARED_GUARDRAILS = [
  '- Treat workspace message, private message, association, company, contact, deal, workflow run, Buy request, WatchTower finding, item, order, purchase order, task, contract, contract template, estimate, invoice, subscription, payment, slip, bill, disbursement, ticket, location, inventory, inventory transaction, custom object record, journal entry, saved view, report, expense, employee, absence, attendance record, payroll profile, payroll run, incentive, property, company pricing, calendar, prospecting, scoring, import, and export requests as live Sanka operations. Results and mutations must come from the dedicated MCP tools above.',
  '- If the user explicitly starts from the installed Sanka plugin chip or names the Sanka plugin, prefer the plugin-attached namespace in the current thread, either `mcp__sanka_plugin__*` or the compatible legacy `mcp__sakura_plugin__*` namespace.',
  '- When the user says Sanka-connected Gmail, connected Gmail, Gmail integration, integration inbox, public message, workspace message, shared inbox, group inbox, workspace inbox, Contact Conversation, or /conversation, use workspace message tools: sync_workspace_messages, list_workspace_messages, get_workspace_message_thread, update_workspace_message_draft for in-place draft edits, and reply_workspace_message_thread only when explicitly asked to send. Do not start with private message tools for those intents.',
  '- Use private message tools only when the user explicitly asks for the authenticated user private/personal/account-level inbox or their own personal connected Gmail.',
  '- For workspace messages, private inbox messages, associations, companies, contacts, deals, workflow runs, Buy requests, WatchTower findings, items, orders, purchase orders, tasks, task projects, job postings, applicants, interviews, organization positions, contracts, contract templates, estimates, invoices, overdue invoices, subscriptions, payments, slips, bills, disbursements, tickets, locations, inventories, inventory transactions, custom object records, expenses, employees, absences, attendance records, payroll profiles, payroll runs, incentives, properties, company pricing, calendar workflows, prospecting, scoring, imports, or exports, call the matching protected tool directly without first calling auth_status or connect_sanka.',
  '- All hosted clients, including Codex and Claude, connect through the Connect Sanka URL returned by connect_sanka or protected tool results. Direct bearer authentication and native MCP OAuth discovery are not supported.',
  '- Do not route plugin-scoped Sanka requests through stale global aliases such as `mcp__sanka_key__*`, `mcp__sanka__*`, or other duplicate global namespaces. Those can bypass the plugin attachment and surface raw auth errors.',
  '- The workspace_id parameter on data tools is not a workspace switcher. It expects the authenticated workspace internal UUID, not the short numeric workspace code shown in Sanka URLs. Usually omit workspace_id; use current_workspace, list_workspaces, and switch_workspace for workspace context or switching.',
  '- Immediately before inviting or canceling a workspace invitation, call current_workspace and pass its exact internal workspace_id as expected_workspace_id. Never rely on an earlier switch_workspace result alone. Use list_workspace_invitations first when the invitation id or current invitation state is ambiguous.',
  '- Call invite_workspace_user only after the user explicitly authorizes the invite and pass confirm=true plus expected_workspace_id. Inviting sends email and may consume a billable seat. Call cancel_workspace_invitation only after explicit authorization and pass confirm=true plus expected_workspace_id. A mismatch must stop the operation without retrying in another workspace.',
  '- Do not render Sanka record numbers as Markdown issue references with a leading hash, for example hash followed by 7. Use safe labels such as "Invoice No. 7", "売上請求番号 7", or the UUID instead.',
  '- For Japanese user-facing replies, use Sanka object names precisely: Order is "受注" and Invoice is "売上請求". Do not translate them as "注文" or "請求書" unless quoting external source text.',
  '- For Japanese user-facing tables, show display labels for internal statuses. For example, status=draft should be shown as "下書き"; include the raw key only when explicitly useful, such as "下書き（draft）".',
  '- Do not say a Sanka tool or API call failed unless the tool result is isError or the structuredContent explicitly contains an error or HTTP status >= 400. If a later tool call succeeds, report the successful state.',
  '- If a protected tool is unavailable in the current client session, say the Sanka MCP server or plugin attachment is missing and ask the user to reconnect rather than guessing.',
  '- Never fabricate live Sanka data or substitute repo-local state, database access, or other out-of-band sources for dedicated Sanka tool results.',
  '- For HubSpot workflow mutations, preview first with dry_run=true and set confirm=true only after explicit user approval. Pass raw platform_payload when exact HubSpot flow JSON is needed.',
];

const HOSTED_ONLY_GUARDRAILS = [
  '- For HubSpot native automation requests such as "when a deal becomes closed won, set amount to 100", use create_workflow or update_workflow with provider=hubspot. Do not look for or invent a create_hubspot_workflow tool.',
];

const FULL_ONLY_GUARDRAILS = [
  '- Do not use search_docs or execute as a fallback for live workspace inbox, private inbox, association, company, contact, deal, workflow run, Buy request, WatchTower finding, item, order, purchase order, task, contract, contract template, estimate, invoice, overdue invoice, subscription, payment, slip, bill, disbursement, ticket, location, inventory, inventory transaction, custom object record, expense, employee, absence, attendance record, payroll profile, payroll run, incentive, property, company pricing, calendar, prospecting, scoring, import, or export work when a dedicated MCP tool covers the request.',
  '- Before refusing a Sanka capability because the local Skill text or currently considered tools appear incomplete, call get_capability_guidance with the user intent. If guidance recommends a tool that is not visible in this client session, say the Sanka Skill or MCP tool catalog may be stale and ask the user to update/reconnect the Sanka plugin or start a fresh session.',
  '- For HubSpot native automation requests such as "when a deal becomes closed won, set amount to 100", first use get_capability_guidance if there is any uncertainty, then use create_workflow or update_workflow with provider=hubspot. Do not look for or invent a create_hubspot_workflow tool. Do not conclude this is unsupported only because preview_workflow/start_workflow are business-process workflow tools.',
];

/**
 * Workflow rules shared by every tool profile. They are served on demand by get_capability_guidance
 * rather than embedded in the initialize instructions.
 */
export const SHARED_WORKFLOW_GUIDANCE = [
  '- Keep CRM queries narrow with search, pagination, workspace filters, or result limits when possible.',
  '- For manual product purchase requests, use the Sanka Buy tools instead of creating Purchase Orders or Bills directly: preview_buy_request when starting from natural language, create_buy_request for the draft, source_buy_request for Shopify Global Catalog sourcing, select_buy_offer with one line selection per request line and acknowledge_fee=true only after explicit buyer acceptance of a quoted Cargo success fee, preview_buy_approval, submit_buy_request with confirm=true, then create_buy_purchase_order with confirm=true when the user approves downstream Company/PO creation.',
  '- For RFQ-based vendor sourcing on a Buy request, call source_buy_request with provider=procurement_rfq and either constraints.procurement_request_id to link an existing procurement request or constraints.vendor_company_ids to create a new RFQ and invite those vendors (optional constraints: rfq_deadline, channels with portal only, message). Then follow the RFQ loop: sync_buy_rfq to reconcile vendor proposals into draft offer snapshots and read invitation status (there is no separate invitation list tool), get_buy_sourcing_run or get_buy_request to compare ingested offers, then select_buy_offer. Re-run sync_buy_rfq to poll for new proposals.',
  '- After create_buy_purchase_order, use prepare_buy_checkout only when the user wants the manual checkout URL, confirm_buy_order only after the user gives the external order id, create_buy_bill only after the user approves Bill creation from the merchant purchase, and preview_buy_accounting to check export readiness without posting journals. Pass evidence_files to create_buy_bill only when the user has uploaded file ids to attach to the Bill. Use get_buy_merchant_purchase to inspect linked Company, Purchase Order, checkout, external order, and Bill ids.',
  '- For Sanka Buy cancellation, call cancel_buy_request only after explicit user confirmation and pass confirm=true.',
  '- Sanka Buy creates Company, Purchase Order, checkout handoff, external order confirmation, and Bill links through dedicated Buy tools. It still does not post Journal entries directly; use preview_buy_accounting first, then accounting/export workflows only after a Bill exists and the user confirms the accounting scope.',
  '- For WatchTower waste review, use list_watchtower_findings with status/finding_type filters and get_watchtower_summary for spend, category, and top-vendor breakdowns. Use update_watchtower_finding to confirm or dismiss a finding (resolved is system-managed), and create_buy_request_from_finding to start the replacement purchase; repeat calls reuse the linked Buy request, and the created draft continues through the normal Sanka Buy flow.',
  '- For Convoy partner onboarding, create the partner first, then invite members only after the user explicitly approves sending email and pass confirm_send=true. Resending invitations also requires explicit approval. Archiving partners and revoking members require confirm=true.',
  '- For Convoy partner billing, create invoice requests only after the user explicitly approves partner notification and pass confirm_send=true. Use submission_due_date to drive the configured reminder schedule. Approve, reject, cancel, or mark paid only after explicit approval; mark-paid records payment evidence and never transfers money.',
  '- For Convoy commissions, call calculate_convoy_commissions with dry_run=true first. Store draft calculations only after explicit approval with dry_run=false and confirm=true. Approving or marking paid requires confirm=true; marking paid records status only.',
  '- For integration-side company/contact/deal counts or lists, use aggregate_records, list_companies, list_contacts, or list_deals with scope=integration, provider=hubspot or provider=salesforce, and channel_id when multiple channels exist. HubSpot deals map to deals; Salesforce opportunities map to deals. For freee/MoneyForward取引先, use list_companies or aggregate_records with scope=integration and provider=freee or provider=moneyforward; accounting partners map to companies. For Sanka custom object rows, use query_records or aggregate_records with scope=sanka, object_type=custom_objects, and custom_object/custom_object_slug set to the custom object slug/internal key or id; display names are accepted as a fallback. Use create_custom_object_record, update_custom_object_record, or archive_custom_object_record for row mutations.',
  '- For HubSpot Deal line items, call preview_workflow with workflow_type=deal_to_estimate, source_record.source_system=hubspot, object_type=deal, and the HubSpot Deal id or URL. Do not use query_records or a generic line_items search to conclude that line items are missing.',
  '- For record association work, use list_associations, create_association, and delete_association. There is no update_association tool; changing an association label should be handled as delete_association followed by create_association so the API can re-check label constraints.',
  '- For date- or stage-filtered integration deals, pass filters to list_deals or query_records instead of fetching all rows. The Sanka API accepts common aliases such as stage/dealstage/StageName and closed_at/closedate/CloseDate for HubSpot and Salesforce deal fields.',
  '- For pipeline movement, shrink, amount decrease, or close-date extension questions, use pipeline snapshot tools: capture_pipeline_snapshot when a new point-in-time baseline is needed, list/get batches to inspect history, compare_pipeline_snapshots for read-only deltas, and sync_pipeline_snapshot_hubspot_properties only after a dry run has been reviewed and the user explicitly confirms the HubSpot writeback.',
  '- For duplicate discovery, use aggregate_records or query_records with mode=dedupe_candidates, match_fields such as ["name"] or ["email"], and a bounded scan_limit before any delete or dedupe mutation.',
  '- For Sanka orders and invoices, delete_order and delete_invoice are soft archive operations. Describe the result as archived / アーカイブ済み, not permanently deleted. Use permanent_delete_order or permanent_delete_invoice only when the user explicitly asks for permanent deletion, the record is already archived, and confirm=true is provided.',
  '- For integration-side HubSpot/Salesforce company create/update/delete/dedupe, use the existing create_company, update_company, or delete_company tools with target=integration or target=both where supported. For freee/MoneyForward取引先 deletion, first list_companies with scope=integration and provider=freee or provider=moneyforward, then call delete_company with target=integration, provider set to the same provider, external_id set to the accounting partner id, dry_run=true; call again with confirm=true only after explicit approval. Do not invent provider-specific tools such as list_freee_partners or list_moneyforward_partners. Run dry_run=true first for Sanka or remote delete and dedupe, inspect sanka_action/warnings/sync_state, and set confirm=true only after the user explicitly approves the destructive action.',
  '- For integration-side HubSpot/Salesforce property schemas, use list_properties or get_property with scope=integration, provider=hubspot or provider=salesforce, and channel_id when multiple channels exist. HubSpot deals map to deals; Salesforce opportunities map to deals.',
  '- For remote property create/update/delete, use create_property, update_property, or delete_property with target=integration or target=both. Run dry_run=true first for remote property writes, and set confirm=true only after the user explicitly approves a delete. Salesforce property writes are limited to custom fields ending in __c.',
  '- For Sanka company cycles, billing_cycle and payment_cycle are standard company fields, not a custom-property creation flow. Set them directly with create_company/update_company top-level inputs: billing_cycle="end" for 月末締め or "1" through "31" for a closing day; payment_cycle="nmonth_end" for 翌月末払い, "cmonth_end" for 当月末払い, or net terms such as "net_30". If the user only says "月末" for payment cycle, ask whether they mean current-month end or next-month end.',
  '- For custom object schema management, use list_object_schemas and mutate_object_schema with scope/target=sanka|integration|both. HubSpot schema writes use HubSpot object schema APIs; Salesforce schema writes use Metadata API. Always run dry_run=true first, and require confirm=true for deletes.',
  '- For app-builder requests, use preview_app_blueprint first and pass language="ja" for Japanese requests. Prefer an exact built-in template when the intent matches CRM, ERP, expense, inventory, procurement, billing, HR, IT asset, project, or support desk. For partial matches such as "車業界向けERP", use the closest template with overlay for adjusted module labels, custom objects, permission sets, and Mermaid artifacts. For completely unknown requests, send an ai_generated blueprint_dsl to preview only; apply it only after the returned validator is valid, the user explicitly approves, confirm=true is set, and allow_generated_blueprint_apply=true is set. apply_app_blueprint mutates global side-menu modules, creates missing custom objects, creates or updates permission sets, and persists generated guide/Mermaid artifacts; pass create_editable_guides=true when those artifacts should also appear as editable manuals in the guide drawer/admin UI. It does not assign users or delete records.',
  '- For rule settings, use approval-rules, lock-rules, and delivery-rules tools with object rather than object-specific endpoints. Use approval rules when a reusable policy gate must wait for approval; use create_approval_request for a one-off approval on a specific record; use lock rules when a matching record should not be edited; use delivery rules when invoice send/schedule readiness or required fields should change. Delivery rules are invoice-only for now.',
  '- For journal-backed P&L, balance sheet, or cash-flow requests, use create_journal_statement_view first to create the saved view, then use list_journal_entries with the returned view_id when you need to read the generated statement rows.',
  '- For normal saved view requests, use create_view/list_views/get_view/get_view_columns/update_view/delete_view instead of object-specific workarounds. Pass object names such as orders, invoices, companies, contacts, deals, tickets, tasks, custom_object, dashboards, or panels.',
  '- For report/dashboard creation, use create_report. Use list_reports/get_report to inspect reports before updates or deletes.',
  '- Use list_workspace_messages for the shared workspace/integration inbox, including Sanka-connected Gmail, Gmail integrations, public messages, the Contact Conversation workspace inbox, and /conversation. Use list_private_messages only for the authenticated user private/personal account-level inbox.',
  '- Use sync_workspace_messages before reviewing recent or latest Gmail from a Sanka workspace/integration inbox, then list_workspace_messages, then get_workspace_message_thread when the user needs message body/history.',
  '- Before update_workspace_message_draft, retrieve the existing thread and read back its message id, subject, body, To, CC, BCC, status, scheduled time, and attachments. Pass a complete replacement payload. The tool preserves the same thread/message/channel/attachments and never authorizes or performs send.',
  '- Start shared workspace/integration inbox detail flows with get_workspace_message_thread when you need the current thread history/body.',
  '- Start private/personal account-level reply flows with get_private_message_thread when you need the current thread history or reply target.',
  '- Call reply_workspace_message_thread or reply_private_message_thread only after the user explicitly asks to send the exact reply, and pass confirm_send=true. Requests to draft, write, compose, revise, or show a reply are not send authorization. Compare distinct send-capable email addresses across both private/personal and current-workspace message channels. If there is one address, expected_sender_email may be omitted. If there are multiple, show the exact body and resolved sender, ask the user to confirm that sender, and pass it as expected_sender_email only after confirmation. If the API returns SENDER_CONFIRMATION_REQUIRED, show available_sender_emails and resolved_sender_email and wait for a new user confirmation; never auto-retry. After success, report the returned sender_email; never infer or substitute a sender identity.',
  '- Use sync_private_messages only when the user asks for the latest state from a private/personal/account-level Gmail or another connected private inbox channel.',
  '- Use get_company_price_table when the user asks for company-specific item pricing, and use search to narrow to one item when possible.',
  '- For create_subscription, use exactly one customer identifier: contact_id, company_id, or customer_id. Company-only customers are valid. When converting invoice or order lines, fetch the source record first and pass line_items/items with item_id when present, or name plus amount/quantity and price/unit_price when no linked item_id exists. Pass tax_rate explicitly for taxable subscriptions, such as tax_rate=10 for standard Japanese consumption tax. The legacy tax field does not replace tax_rate; common Japanese legacy values 0, 8, and 10 are only mirrored when tax_rate is omitted. For subscription-level record discounts, pass discount_id for a registered discount or discount_value plus discount_number_format, such as % or USD, for a manual discount.',
  '- For leave requests such as vacation, PTO, sick leave, or absences, use create_absence/list_absences/get_absence/update_absence/delete_absence rather than tasks or calendar bookings.',
  '- For employee work attendance and time tracking, use list_attendance_records/get_attendance_record/create_attendance_record/update_attendance_record/delete_attendance_record; reserve create_calendar_attendance for public event booking only.',
  '- For payroll setup and calculations, use list_payroll_profiles/upsert_payroll_profile and list_payroll_runs/get_payroll_run/calculate_payroll_run. Use create_payroll_journal_entry when the user wants a monthly payroll run posted to Sanka Journal Entries. Use download_payroll_payslip_pdf when the user explicitly asks for payroll payslip PDFs. Use approve_payroll_run only after explicit user confirmation.',
  '- Keep item, subscription, payment, location, inventory, and inventory transaction queries narrow with workspace filters and local limits because those public endpoints return arrays.',
  '- For item availability questions, call list_items with search for the item name, then list_inventories with search and a small limit. Use list result fields such as total_inventory, available, committed, unavailable, and item_ids before calling get_inventory; only call get_inventory when the list row is insufficient.',
  '- Prefer list_deal_pipelines before describing deal stages so stage labels and ordering match the workspace configuration.',
  '- Use get_estimate for normal estimate lookups. Only use download_estimate_pdf when the user explicitly asks for a PDF, file, attachment, download, or rendered PDF inspection.',
  '- For Sanka Contract templates, use list_contract_templates to inspect available templates, download_contract_template when the user asks for a template file, and upload_contract_template for new PDF/DOC/DOCX templates. Template uploads expect filename plus content_base64, are limited to 20 MiB decoded payloads, and must not assume the hosted MCP server can read a client-local file path.',
  '- For Sanka Contract signing flows, create a draft with upload_contract_pdf or create_contract_from_template, optionally use replace_contract_pdf while it remains a draft, then use update_contract_metadata when needed, save_contract_recipients for signers and non-signing CC recipients, save_contract_place_fields, get_contract_workflow_state for readiness, and send_contract_request or schedule_contract_request for delivery. Sending or scheduling can email external signers and CC recipients, so call those tools only after explicit user approval and pass confirm=true.',
  '- For Sanka object URL requests, call the matching get_* tool when needed and return app_url from the object payload or workflow-created record result. Do not ask the user to copy the URL from the Sanka UI when app_url is present.',
  '- PDF download tools return download_complete=true plus content_base64 for small files. For large files, download_complete=false and content_base64_available=false; this is not a completed user download. If download_url is present, fetch that URL directly and attach or save the PDF before telling the user the download is complete. Only call read_binary_download_chunk when download_url is absent or the direct download fails; then concatenate content_base64 chunks in order, decode the combined base64 string, and attach or save the decoded PDF. Do not call resources/read for resource://tool-response.',
  '- For invoice email sending, use send_invoice_email rather than changing invoice status. For draft emails, pass action="draft". To replace generated PDFs on an existing draft without creating another thread or changing its recipients, subject, body, or channel, pass action="draft" plus replace_draft_message_id and omit to, cc, subject, body, scheduled_at, and channel_id; this never sends the email. To send an existing Sanka invoice-email draft, pass action="send" and send_draft_message_id; omit recipient, subject, body, template, attachment, and channel fields so the saved sender/channel, thread, message fields, and attachments are preserved. To schedule an existing draft in place, pass action="schedule", scheduled_at, and schedule_draft_message_id; omit recipient, subject, body, template, attachment, and channel fields. Confirm the returned from_email, reply_to_email, provider, and history_locations. A saved Gmail/SMTP channel is preserved; a draft without a channel uses the managed invoice sender. For new scheduled sends, pass action="schedule" and scheduled_at as an ISO datetime in the user/workspace timezone. To attach generated PDFs such as an invoice plus delivery note, pass additional_pdf_attachments with template_select, object_type, record_id, and filename as needed.',
  '- For document sender blocks, pass send_from directly to create_order/update_order, create_estimate/update_estimate, and create_invoice/update_invoice when the PDF template uses the send_from field.',
  '- If a PDF download returns 404 after the record was visible earlier, verify current_workspace/list_workspaces and use switch_workspace with the internal workspace UUID before retrying. Record numbers and UUID lookups are workspace-context dependent; do not retry numeric IDs in a different workspace as if they were globally safe.',
  '- For subscription record edits such as start date, end date, status, linked contract changes, or record-level discounts, use update_subscription directly. Pass start_date/end_date as ISO dates; pass end_date=null only when the user explicitly wants to clear the end date and keep the subscription open-ended. Pass contract_id or contract_ids for Sanka Contract associations; pass an empty contract_ids array only when the user explicitly wants to clear linked contracts. Use clear_discount=true only when the user explicitly wants to remove the subscription-level discount.',
  '- For lead-to-cash workflow requests like creating or previewing an estimate from a deal, use preview_workflow directly when the user gives a HubSpot Deal URL; pass workflow_type=deal_to_estimate, source_record.source_system=hubspot, object_type=deal, and source_record.url. Do not ask the user to explain Sanka sync behavior. The API will use a synced Sanka deal if available, otherwise use authorized HubSpot access for read-only preview and supported execution. If the HubSpot deal has an unmapped associated company, pass options.allow_missing_customer_create=true to preview the Sanka company creation candidate, explain that creating/linking that company requires user approval, and pass options.confirm_create_missing_customer=true to start_workflow only after that explicit approval. Use resolve_record only when the source phrase is ambiguous and no URL/id is present. Use start_workflow to create the estimate draft and approval request only after explicit user confirmation, and get_workflow_run for status.',
  '- For CRM-origin invoice requests such as "create an invoice from this HubSpot Deal" or Salesforce Opportunity billing, do not call deal_to_invoice or create_invoice directly from the CRM record. Preview the source with workflow_type=deal_to_order, tell the user that Sanka will first create or reuse a Sanka Order so billing can be generated correctly, ask for explicit confirmation, then start_workflow with workflow_type=deal_to_order. Create invoices only from the resulting Sanka Order with workflow_type=order_to_invoice. Accounting sync is a separate invoice_export workflow step; after creating invoices from Orders, preview invoice_export with sync_scope=created_in_workflow_run or selected_invoice_ids and target_system=freee or moneyforward, then start invoice_export only after explicit user approval.',
  '- For Sanka Estimate invoice requests such as "create an invoice from this estimate", use workflow_type=estimate_to_invoice with source_record.source_system=sanka, object_type=estimate, and the Sanka Estimate id. Explain that Sanka will create or reuse a Sanka Order from the Estimate before creating the Invoice.',
  '- For CRM-origin subscription requests such as "create subscriptions from HubSpot Deals" or "bulk-create subscriptions from deals with a subscription flag", use workflow_type=deal_to_subscription. For HubSpot batch lists, pass source_record.source_system=hubspot, object_type=deal, portal_id or channel_id, and options such as subscription_flag_property plus subscription_flag_value or subscription_flag_values. Preview first, explain that Sanka will create or reuse Orders before creating Subscriptions, then start only after explicit confirmation.',
  '- For Sanka Subscription invoice requests such as "create invoices from these subscriptions", use workflow_type=subscription_to_invoice with source_record.source_system=sanka, object_type=subscription, and one record_id or options.subscription_ids for a batch. Pass start_date and due_date when the user gives the target billing period or payment terms. Preview first when the scope is broad or ambiguous.',
  '- For CRM-origin procurement requests such as "if this HubSpot Deal lacks inventory, create a purchase order", do not create a purchase order directly from the CRM deal/opportunity. First route the CRM record through deal_to_order, explain that Sanka will create or reuse the Sanka Order first, ask for explicit confirmation, then use workflow_type=order_to_purchase_order with the resulting Sanka Order. order_to_purchase_order previews shortage lines and creates purchase orders only for detected inventory shortages.',
  '- For Disbursement to Expense or Bill payable links, use list_disbursement_allocations/create_disbursement_allocation/update_disbursement_allocation/delete_disbursement_allocation. Do not use generic association tools for Expense <> Disbursement because that relationship is DisbursementPayableAllocation-backed.',
  '- For HubSpot order or fulfillment handoff requests such as "move this HubSpot deal to order processing", "create an order draft from this HubSpot Deal", "preview fulfillment handoff", or "check inventory and delivery timing", call preview_workflow with workflow_type=deal_to_order_handoff, source_record.source_system=hubspot, object_type=deal, and the HubSpot Deal id or URL. Summarize customer/contact resolution, line items, inventory availability, shortages, lead-time and delivery timing, duplicate order or handoff warnings, blockers, and required_confirmation. Missing inventory or lead-time data is a limitation to report, not a reason to invent data. Call start_workflow only after explicit confirmation; pass a stable idempotency_key and allow_duplicate_order only when the user explicitly approved another order. HubSpot writeback happens only after successful Sanka order or handoff creation.',
  '- For freee or Money Forward invoice draft sync requests, use preview_workflow with workflow_type=invoice_export, source_record.source_system=sanka, source_record.object_type=invoice, options.target_system=freee or moneyforward, and an explicit sync_scope. Prefer created_in_workflow_run after an order_to_invoice run or selected_invoice_ids for user-selected invoices. If an accounting channel id is needed, call list_integration_channels with provider=freee or moneyforward only to discover channel_id candidates, then pass the selected channel_id as freee_channel_id or moneyforward_channel_id to preview_workflow/start_workflow. Do not use integration-sync shadow_mode, rollout_stage, is_enabled, outbound_pipeline_active, export_ready, or export_blocker fields from list_integration_channels to decide invoice_export availability; preview_workflow/start_workflow returns the actual accounting export blockers, provider capabilities, and next_actions. If the user only says to sync Sanka invoices to accounting drafts without a scope, do not call start_workflow; preview returns needs_confirmation with options, or ask the user to choose. all_eligible_unsynced requires confirm_all=true and explicit user confirmation. For freee repeats, never tell the user to delete the freee invoice: freee records are cancelled/restorable rather than physically deleted. Use allow_resync=true to update the mapped draft/unregistered invoice, or allow_multiple_freee_drafts=true only when the user explicitly wants a separate draft. For Money Forward repeats after the mapped Money Forward draft was deleted remotely and the provider returned not_found, pass allow_recreate_moneyforward_draft=true only after the user explicitly asks to create a replacement; the API first tries the mapped draft and creates a replacement only on Money Forward not_found. Other re-sync or multiple accounting draft requests require allow_resync or provider-supported duplicate flags plus user intent.',
  '- For QuickBooks Online Invoice export requests, use preview_workflow with workflow_type=invoice_export, source_record.source_system=sanka, source_record.object_type=invoice, options.target_system=quickbooks_online, and an explicit invoice sync scope. Pass the QuickBooks channel id when multiple connections exist. qbo_customer_id and qbo_item_id may be supplied explicitly; otherwise the accounting runtime uses its configured customer and item resolution. Start only after preview or explicit user confirmation.',
  '- For QuickBooks Online Bill export requests, use preview_workflow with workflow_type=bill_export, source_record.source_system=sanka, source_record.object_type=bill, options.target_system=quickbooks_online, and an explicit sync_scope such as selected_bill_ids. Pass the QuickBooks channel id when multiple connections exist and qbo_expense_account_id for the required expense-account mapping; qbo_ap_account_id is optional and otherwise QuickBooks uses its default Accounts Payable account. Start only after preview or explicit user confirmation, use a stable idempotency_key, and set allow_resync=true only when the user intends to update an existing mapped QuickBooks Bill. Paid Sanka Bills are blocked because QuickBooks BillPayment is a separate workflow.',
  '- For HubSpot revenue control questions such as "summarize this month\'s HubSpot revenue", "show unbilled deals", "show approval waits", "show unpaid invoices", or "what revenue is blocked?", call preview_workflow with workflow_type=revenue_control_summary, source_record.source_system=hubspot, object_type=deal, and options for start_date/end_date or date_range. Summarize won, quote_drafted, approval_pending, unbilled, invoiced, unpaid, blocked, totals by currency/owner/customer/aging, top_blockers, and next_actions. This is read-only; do not call start_workflow or mutate HubSpot, Sanka, freee, or Stripe records. For sales incentive or commission questions such as "calculate April commissions", "calculate this month sales incentives by rep", "show draft commissions", or "flag unpaid or low-margin deals", call preview_workflow with workflow_type=sales_incentive_commission, source_record.source_system=hubspot, object_type=deal, and options for period/date range, channel_id, CRM owner/rep/customer filters, include_records/include_excluded, include_payment_status, include_margin, include_refunds, and compensation_rule_id or plan_id when needed. Summarize total reps, included/excluded/flagged deals, eligible and commission totals by currency, rule version/snapshot, rep summaries, deal explanations, unpaid/refund/low-margin/unmapped exceptions, warnings, and suggested next actions. This is draft/read-only; do not call start_workflow or mutate HubSpot, Salesforce, Sanka invoices/orders/payments, freee, Stripe, platform mappings, compensation rules, payouts, or approvals.',
  '- For Salesforce quote-readiness questions such as "Can this Salesforce Opportunity be quoted?", call preview_workflow with workflow_type=quote_readiness, source_record.source_system=salesforce, object_type=opportunity, and the Salesforce Opportunity id or URL. The tool routes this read-only CPQ business preview through Sanka quote-readiness routes where Salesforce is the source platform. Summarize ready, target_record, financials, line item checks, approval, hard_blockers, warnings, suggested_fixes, source_records, sanka_records, and orchestration_plan. Do not call Salesforce-specific all-in-one create tools; compose generic Sanka search/create/estimate/workflow tools only when a later create flow is explicitly supported and requested.',
  '- For orders, provide line items inside the nested `order` payload and prefer external references for linked companies or items when available.',
  '- For purchase orders, slips, bills, and disbursements, prefer linked company or contact ids/external references when the user already has those records in Sanka.',
  '- Prefer get_item before applying company price overrides when you need to confirm the default item price or item identity.',
  '- Use list_tasks or get_task before updating a task when the user wants to append to the current description, because task updates replace the field you send.',
  '- Prefer list_ticket_pipelines before moving tickets across stages so stage keys and labels match the workspace configuration.',
  '- Prefer list_properties or get_property before mutating object records or property definitions when you need to confirm the current schema.',
  '- Start booking, rescheduling, or cancellation flows with get_calendar_bootstrap when you need the event context or existing attendance details.',
  '- Use check_calendar_availability before create_calendar_attendance or reschedule_calendar_attendance when the user needs the next available slot.',
  '- Prefer update_ticket_status over update_ticket when only the stage or status is changing.',
  '- Use prospect_companies when the user wants external company discovery or target-account research rather than only searching existing CRM records.',
  '- Use score_record when the user wants qualification, prioritization, or a transparent explanation of why a company or deal is strong or weak.',
  '- Use generate_demo_workspace when the user wants a fast sandbox or reproducible demo workspace with realistic lead-to-cash data. For direct HubSpot/Salesforce demo creation, call it with target=integration, provider, dry_run=true first, then confirm=true only after explicit approval. For provider custom object demo records, pass custom_objects with external_object_type and records or count/name_property; the custom object schema must already exist.',
  '- Use push_integration_sync after a user edits or seeds records and explicitly wants those changes pushed to a connected downstream system.',
  '- Use browser_use only for registered browser workflows when a third-party API cannot perform the requested operation. For HubSpot demo company avatars, use workflow="demo.hubspot.company_avatar", driver="agent_browser", dry_run=true first, then run with dry_run=false and confirm=true only after the dry run is reviewed. Do not use browser_use for open-ended browsing or arbitrary web instructions.',
  '- HubSpot company avatar note: hs_logo_url can be updated by API but does not control the visible round record/list avatar. The visible avatar is backed by HubSpot-managed state such as hs_avatar_filemanager_key, which is read-only through public CRM property updates, so demo avatar updates must go through the registered browser workflow or be left as default HubSpot icons.',
  '- When a create tool returns a governance advisory such as missing_recommended_partner, report that the record was created and ask for explicit permission before creating or linking a company/contact.',
  '- Use upload_expense_attachment before create_expense or update_expense when the user wants a receipt or invoice attached.',
  '- upload_expense_attachment expects filename plus content_base64. Do not assume the hosted MCP server can read a client-local file path. For ordinary receipt or invoice PDFs, upload the original file bytes as-is; do not skip attachment, compress the PDF, rasterize it, or replace it with extracted text merely because the base64 payload is hundreds of KB. Only use a text surrogate after the original upload actually fails.',
  '- If a client-local expense attachment base64 string would be truncated or unreliable in one upload_expense_attachment call, use start_expense_attachment_upload, append_expense_attachment_upload_chunk, and finish_expense_attachment_upload instead of browser UI fallbacks or PDF compression. Use the returned chunk_size as the normal target; ordinary receipt PDFs should usually take one append call, not many tiny chunks. Pass the returned file_id to create_expense or update_expense.',
  '- For expense intake with a receipt or invoice, upload the attachment first, pass the returned file_id through attachment_file_ids on create_expense or update_expense, then call get_expense if the user needs base-currency/readback confirmation.',
  '- For foreign-currency expenses, preserve amount and currency. Set base_currency only when the user, receipt, payment record, or another authoritative source supplies the workspace-base amount; an explicit base_currency overrides automatic conversion. Read the expense back with get_expense when the exact base amount matters.',
  '- Use upload_bill_attachment before create_bill or update_bill when the user wants a bill file attached.',
  '- upload_bill_attachment expects filename plus content_base64. If a client-local bill PDF base64 string would be truncated or unreliable in one upload_bill_attachment call, use start_bill_attachment_upload, append_bill_attachment_upload_chunk, and finish_bill_attachment_upload instead of browser UI fallbacks or PDF compression. Use the returned chunk_size as the normal target and pass the returned file_id in create_bill or update_bill.',
  '- Use list_employees to resolve the full employee directory. Do not infer employees from absences, attendance records, or payroll profiles because those only show employees with related HR records.',
  '- Use upload_order_attachment, upload_purchase_order_attachment, upload_estimate_attachment, or upload_invoice_attachment before the matching create/update tool when the user wants a file attached.',
  "- Document attachment upload tools expect filename plus content_base64. Do not assume the hosted MCP server can read a client-local file path. If a client-local order, purchase order, estimate, or invoice attachment base64 string would be truncated or unreliable in one direct upload call, use that object family's start_*_attachment_upload, append_*_attachment_upload_chunk, and finish_*_attachment_upload tools instead of browser UI fallbacks or replacing the file with extracted text.",
  '- Contract template/PDF upload tools expect filename plus content_base64. Upload the original PDF/DOC/DOCX or PDF bytes as-is rather than replacing the document with extracted text.',
  '- For partner commissions, resolve the partner company id with list_incentive_company_options or list_companies, create an invoice_paid company-payee rule with create_incentive_plan, run calculate_incentives with dry_run=true first, then set dry_run=false only when the user wants draft incentives stored. Use approve_incentives only after explicit approval.',
  '- Use generate_incentive_payment_notice when the user asks for a partner payment request or invoice-request notice from calculated incentives.',
  '- Use upload_import_file before import_records when the user starts from a local CSV or spreadsheet export. For HubSpot Deal to Sanka Order imports, use import_records with object_type=order, source_kind=integration, provider=hubspot, and record_ids.',
  '- Use retry_import_job or retry_export_job when the user wants to retry a failed or canceled public transfer job.',
  '- Use list_integration_channels before export_records when the user does not already know the destination channel_id.',
  '- Use connect_sanka when the user explicitly asks to connect or reconnect Sanka without retrying a protected action first.',
  '- If a protected tool reports missing authentication and structuredContent.required_user_facing_reply is present, include that field verbatim in the next visible response before stopping; it contains the exact full Connect Sanka URL. Do not omit the URL, hide it behind a short label like "Connect Sanka", abbreviate the token, replace it with "...", or only tell the user to reconnect. If the field is missing, call auth_status so the tool result can surface reconnect metadata. Do not fabricate login URLs. Then tell the user to retry after reconnecting.',
  '- Individual HTTP requests to the API have a 30-second timeout. If a request times out, try a smaller query or add filters.',
];

const FULL_ONLY_WORKFLOW_GUIDANCE = [
  '- Use search_docs before writing code when you need to discover the right SDK method or parameter shape for uncovered workflows.',
  '- Use execute only for Sanka SDK workflows that are not covered by dedicated MCP tools.',
  '- Code execution has a total timeout of approximately 5 minutes. If your code times out, simplify it or break it into smaller steps.',
];

/**
 * Returns the workflow rules that apply to a tool profile.
 */
export function getWorkflowGuidance(toolProfile: ToolProfile = 'full'): string[] {
  return toolProfile === 'hosted' ?
      [...SHARED_WORKFLOW_GUIDANCE]
    : [...SHARED_WORKFLOW_GUIDANCE, ...FULL_ONLY_WORKFLOW_GUIDANCE];
}

/**
 * Builds the default initialize instructions for a tool profile.
 */
export function buildDefaultInstructions(toolProfile: ToolProfile = 'full'): string {
  const intro = toolProfile === 'hosted' ? HOSTED_INTRO : FULL_INTRO;
  const guardrails =
    toolProfile === 'hosted' ?
      [...SHARED_GUARDRAILS, ...HOSTED_ONLY_GUARDRAILS]
    : [...SHARED_GUARDRAILS, ...FULL_ONLY_GUARDRAILS];
  return [...intro, '', 'Guardrails:', ...guardrails].join('\n');
}

const DEFAULT_FULL_INSTRUCTIONS = buildDefaultInstructions('full');
const DEFAULT_HOSTED_INSTRUCTIONS = buildDefaultInstructions('hosted');

interface InstructionsCacheEntry {
  fetchedInstructions: string;
  fetchedAt: number;
}

const instructionsCache = new Map<string, InstructionsCacheEntry>();

export async function getInstructions({
  customInstructionsPath,
  toolProfile = 'full',
}: {
  customInstructionsPath?: string | undefined;
  toolProfile?: ToolProfile | undefined;
}): Promise<string> {
  const now = Date.now();
  const cacheKey = `${customInstructionsPath ?? '__default__'}:${toolProfile}`;
  const cached = instructionsCache.get(cacheKey);

  if (cached && now - cached.fetchedAt <= INSTRUCTIONS_CACHE_TTL_MS) {
    return cached.fetchedInstructions;
  }

  // Evict stale entries so the cache doesn't grow unboundedly.
  for (const [key, entry] of instructionsCache) {
    if (now - entry.fetchedAt > INSTRUCTIONS_CACHE_TTL_MS) {
      instructionsCache.delete(key);
    }
  }

  let fetchedInstructions: string;

  if (customInstructionsPath) {
    fetchedInstructions = await fetchLatestInstructionsFromFile(customInstructionsPath);
  } else {
    fetchedInstructions = toolProfile === 'hosted' ? DEFAULT_HOSTED_INSTRUCTIONS : DEFAULT_FULL_INSTRUCTIONS;
  }

  instructionsCache.set(cacheKey, { fetchedInstructions, fetchedAt: now });
  return fetchedInstructions;
}

async function fetchLatestInstructionsFromFile(path: string): Promise<string> {
  try {
    return await fs.readFile(path, 'utf-8');
  } catch (error) {
    getLogger().error({ error, path }, 'Error fetching instructions from file');
    throw error;
  }
}
