// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import fs from 'fs/promises';
import { getLogger } from './logger';
import { ToolProfile } from './profile';

const INSTRUCTIONS_CACHE_TTL_MS = 15 * 60 * 1000; // 15 minutes
const DEFAULT_FULL_INSTRUCTIONS = [
  'This is the Sanka MCP server.',
  '',
  'Available tools:',
  '- connect_sanka: Start or resume the Sanka OAuth connection flow when the user explicitly asks to connect or reconnect Sanka.',
  '- search_docs: Search SDK documentation to find the right methods and parameters.',
  '- execute: Run TypeScript code against a pre-authenticated SDK client. Define an async run(client) function.',
  '- auth_status: Debug whether the Sanka connector is authenticated. Do not use this as a preflight before protected Sanka tools.',
  '- list_private_messages: Review the authenticated user private inbox threads in Sanka.',
  '- sync_private_messages: Pull the latest private inbox threads into Sanka.',
  '- get_private_message_thread: Load one private inbox thread and its message history.',
  '- reply_private_message_thread: Send a reply on a private inbox thread.',
  '- archive_private_message_thread: Archive a private inbox thread.',
  '- list_companies: Search and review companies in Sanka.',
  '- get_company: Load one company in Sanka.',
  '- create_company: Create a company in Sanka.',
  '- update_company: Update a company in Sanka.',
  '- delete_company: Delete a company in Sanka.',
  '- get_company_price_table: Load company-level item pricing for one company.',
  '- update_company_price_table_company: Update the company-wide price-table mode or default company percentage.',
  '- update_company_price_table_item: Set or clear a company-specific price override for one item.',
  '- apply_company_price_table_items: Apply one company-level percentage override across all items for a company.',
  '- list_contacts: Search and review contacts in Sanka.',
  '- get_contact: Load one contact in Sanka.',
  '- create_contact: Create a contact in Sanka.',
  '- update_contact: Update a contact in Sanka.',
  '- delete_contact: Delete a contact in Sanka.',
  '- list_deals: Review deals (sales pipeline records) in Sanka.',
  '- get_deal: Load one deal in Sanka.',
  '- create_deal: Create a deal in Sanka.',
  '- update_deal: Update a deal in Sanka.',
  '- delete_deal: Delete a deal in Sanka.',
  '- list_deal_pipelines: List the deal pipelines and stages defined in the workspace.',
  '- list_items: Review items in Sanka.',
  '- get_item: Load one item in Sanka.',
  '- create_item: Create an item in Sanka.',
  '- update_item: Update an item in Sanka.',
  '- delete_item: Delete an item in Sanka.',
  '- list_orders: Search and review orders in Sanka.',
  '- get_order: Load one order in Sanka.',
  '- create_order: Create an order in Sanka.',
  '- update_order: Update an order in Sanka.',
  '- delete_order: Delete an order in Sanka.',
  '- list_purchase_orders: Review purchase orders in Sanka.',
  '- get_purchase_order: Load one purchase order in Sanka.',
  '- create_purchase_order: Create a purchase order in Sanka.',
  '- update_purchase_order: Update a purchase order in Sanka.',
  '- delete_purchase_order: Delete a purchase order in Sanka.',
  '- list_tasks: Search and review tasks in Sanka.',
  '- get_task: Load one task in Sanka.',
  '- create_task: Create a task in Sanka.',
  '- update_task: Update an existing task in Sanka.',
  '- delete_task: Delete a task in Sanka.',
  '- list_estimates: Review estimates in Sanka.',
  '- get_estimate: Load one estimate in Sanka.',
  '- download_estimate_pdf: Download one estimate as a PDF document.',
  '- create_estimate: Create an estimate in Sanka.',
  '- update_estimate: Update an estimate in Sanka.',
  '- delete_estimate: Delete an estimate in Sanka.',
  '- list_invoices: Review invoices in Sanka.',
  '- list_overdue_invoices: Review overdue invoices in Sanka that still have outstanding balance.',
  '- get_invoice: Load one invoice in Sanka.',
  '- download_invoice_pdf: Download one invoice as a PDF document.',
  '- list_payments: Review payments in Sanka.',
  '- get_payment: Load one payment in Sanka.',
  '- create_payment: Create a payment in Sanka.',
  '- update_payment: Update a payment in Sanka.',
  '- delete_payment: Delete a payment in Sanka.',
  '- download_payment_pdf: Download one payment as a PDF document.',
  '- list_slips: Review slips in Sanka.',
  '- get_slip: Load one slip in Sanka.',
  '- create_slip: Create a slip in Sanka.',
  '- update_slip: Update a slip in Sanka.',
  '- delete_slip: Delete a slip in Sanka.',
  '- download_slip_pdf: Download one slip as a PDF document.',
  '- list_bills: Review bills in Sanka.',
  '- get_bill: Load one bill in Sanka.',
  '- create_bill: Create a bill in Sanka.',
  '- update_bill: Update a bill in Sanka.',
  '- delete_bill: Delete a bill in Sanka.',
  '- list_disbursements: Review disbursements in Sanka.',
  '- get_disbursement: Load one disbursement in Sanka.',
  '- create_disbursement: Create a disbursement in Sanka.',
  '- update_disbursement: Update a disbursement in Sanka.',
  '- delete_disbursement: Delete a disbursement in Sanka.',
  '- download_order_pdf: Download one order as a PDF document.',
  '- create_invoice: Create an invoice in Sanka.',
  '- update_invoice: Update an invoice in Sanka.',
  '- delete_invoice: Delete an invoice in Sanka.',
  '- list_subscriptions: Review subscriptions in Sanka.',
  '- get_subscription: Load one subscription in Sanka.',
  '- create_subscription: Create a subscription in Sanka.',
  '- update_subscription: Update a subscription in Sanka.',
  '- delete_subscription: Delete a subscription in Sanka.',
  '- list_payments: Review payments in Sanka.',
  '- get_payment: Load one payment in Sanka.',
  '- create_payment: Create a payment in Sanka.',
  '- update_payment: Update a payment in Sanka.',
  '- delete_payment: Delete a payment in Sanka.',
  '- list_tickets: Review tickets in Sanka.',
  '- get_ticket: Load one ticket in Sanka.',
  '- create_ticket: Create a ticket in Sanka.',
  '- update_ticket: Update a ticket in Sanka.',
  '- delete_ticket: Delete a ticket in Sanka.',
  '- list_ticket_pipelines: List the ticket pipelines and stages defined in the workspace.',
  '- update_ticket_status: Update only the stage or status of a ticket in Sanka.',
  '- list_locations: Review locations in Sanka.',
  '- get_location: Load one location in Sanka.',
  '- create_location: Create a location in Sanka.',
  '- update_location: Update a location in Sanka.',
  '- delete_location: Delete a location in Sanka.',
  '- list_inventories: Review inventories in Sanka.',
  '- get_inventory: Load one inventory in Sanka.',
  '- create_inventory: Create an inventory record in Sanka.',
  '- update_inventory: Update an inventory record in Sanka.',
  '- delete_inventory: Delete an inventory record in Sanka.',
  '- list_inventory_transactions: Review inventory transactions in Sanka.',
  '- get_inventory_transaction: Load one inventory transaction in Sanka.',
  '- create_inventory_transaction: Create an inventory transaction in Sanka.',
  '- update_inventory_transaction: Update an inventory transaction in Sanka.',
  '- delete_inventory_transaction: Delete an inventory transaction in Sanka.',
  '- list_expenses: Review expense records in Sanka.',
  '- get_expense: Load one expense in Sanka.',
  '- upload_expense_attachment: Upload an expense attachment and return a file_id.',
  '- upload_import_file: Upload a CSV or similar import file and return a file_id.',
  '- import_records: Create a public import job from an uploaded file.',
  '- get_import_job: Load one import job by id.',
  '- list_import_jobs: List recent import jobs.',
  '- cancel_import_job: Cancel a running import job.',
  '- list_integration_channels: List connected export destinations and return channel ids.',
  '- export_records: Create a public export job for Sanka records.',
  '- get_export_job: Load one export job by id.',
  '- list_export_jobs: List recent export jobs.',
  '- cancel_export_job: Cancel a running export job.',
  '- create_expense: Create an expense in Sanka.',
  '- update_expense: Update an existing expense in Sanka.',
  '- delete_expense: Delete an expense in Sanka.',
  '- list_properties: Review object property definitions in Sanka.',
  '- get_property: Load one property definition in Sanka.',
  '- create_property: Create a custom property in Sanka.',
  '- update_property: Update a custom property in Sanka.',
  '- delete_property: Delete a custom property in Sanka.',
  '- get_calendar_bootstrap: Load the public calendar booking context for an event or attendance.',
  '- check_calendar_availability: Check available booking slots for a public calendar event.',
  '- create_calendar_attendance: Book a new public calendar attendance.',
  '- cancel_calendar_attendance: Cancel an existing public calendar attendance.',
  '- reschedule_calendar_attendance: Reschedule an existing public calendar attendance.',
  '- prospect_companies: Discover net-new companies from external sources using Sanka prospecting.',
  '- score_record: Score a company or deal in Sanka and explain the result.',
  '- generate_demo_workspace: Seed a workspace with curated demo CRM and billing data.',
  '- push_integration_sync: Emit outbound sync jobs for records to a connected integration channel.',
  '',
  'Guardrails:',
  '- Treat private message, company, contact, deal, item, order, purchase order, task, estimate, invoice, subscription, payment, slip, bill, disbursement, ticket, location, inventory, inventory transaction, expense, property, company pricing, calendar, prospecting, scoring, import, and export requests as live Sanka operations. Results and mutations must come from the dedicated MCP tools above.',
  '- If the user explicitly starts from the installed Sanka Plugin chip or names the Sanka Plugin, prefer the plugin-attached Sanka namespace in the current thread, usually `mcp__sanka_plugin__*`.',
  '- For private inbox messages, companies, contacts, deals, items, orders, purchase orders, tasks, estimates, invoices, overdue invoices, subscriptions, payments, slips, bills, disbursements, tickets, locations, inventories, inventory transactions, expenses, properties, company pricing, calendar workflows, prospecting, scoring, imports, or exports, call the matching protected tool directly without first calling auth_status or connect_sanka.',
  '- Protected Sanka tool calls are the OAuth trigger in clients like Codex, Claude, and Cursor.',
  '- Do not route plugin-scoped Sanka requests through stale global aliases such as `mcp__sanka_key__*`, `mcp__sanka__*`, or other duplicate global Sanka namespaces. Those can bypass the plugin attachment and surface raw auth errors.',
  '- Do not use search_docs or execute as a fallback for live private inbox, company, contact, deal, item, order, purchase order, task, estimate, invoice, overdue invoice, subscription, payment, slip, bill, disbursement, ticket, location, inventory, inventory transaction, expense, property, company pricing, calendar, prospecting, scoring, import, or export work when a dedicated MCP tool covers the request.',
  '- If a protected tool is unavailable in the current client session, say the Sanka MCP server or plugin attachment is missing and ask the user to reconnect rather than guessing.',
  '- Never fabricate live Sanka data or substitute repo-local state, database access, or other out-of-band sources for dedicated Sanka tool results.',
  '',
  'Workflow:',
  '- Use search_docs before writing code when you need to discover the right SDK method or parameter shape for uncovered workflows.',
  '- Use execute only for Sanka SDK workflows that are not covered by dedicated MCP tools.',
  '- Keep CRM queries narrow with search, pagination, workspace filters, or result limits when possible.',
  '- Use list_private_messages for the private account-level inbox. Do not confuse it with Sanka shared group inbox workflows.',
  '- Start reply flows with get_private_message_thread when you need the current thread history or reply target.',
  '- Use sync_private_messages before replying when the user asks for the latest state from Gmail or another connected private inbox channel.',
  '- Use get_company_price_table when the user asks for company-specific item pricing, and use search to narrow to one item when possible.',
  '- Keep item, subscription, payment, location, inventory, and inventory transaction queries narrow with workspace filters and local limits because those public endpoints return arrays.',
  '- Prefer list_deal_pipelines before describing deal stages so stage labels and ordering match the workspace configuration.',
  '- For orders, provide line items inside the nested `order` payload and prefer external references for linked companies or items when available.',
  '- For purchase orders, slips, bills, and disbursements, prefer linked company or contact ids/external references when the user already has those records in Sanka.',
  '- Prefer get_item before applying company price overrides when you need to confirm the default item price or item identity.',
  '- Use list_tasks or get_task before updating a task when the user wants to append to the current description, because task updates replace the field you send.',
  '- Prefer list_ticket_pipelines before moving tickets across stages so stage keys and labels match the workspace configuration.',
  '- Prefer list_properties or get_property before mutating object records when you need to confirm the current schema.',
  '- Start booking, rescheduling, or cancellation flows with get_calendar_bootstrap when you need the event context or existing attendance details.',
  '- Use check_calendar_availability before create_calendar_attendance or reschedule_calendar_attendance when the user needs the next available slot.',
  '- Prefer update_ticket_status over update_ticket when only the stage or status is changing.',
  '- Use prospect_companies when the user wants external company discovery or target-account research rather than only searching existing CRM records.',
  '- Use score_record when the user wants qualification, prioritization, or a transparent explanation of why a company or deal is strong or weak.',
  '- Use generate_demo_workspace when the user wants a fast sandbox or reproducible demo workspace with realistic lead-to-cash data.',
  '- Use push_integration_sync after a user edits or seeds records and explicitly wants those changes pushed to a connected downstream system.',
  '- Use upload_expense_attachment before create_expense or update_expense when the user wants a receipt or invoice attached.',
  '- upload_expense_attachment expects filename plus content_base64. Do not assume the hosted MCP server can read a client-local file path.',
  '- Use upload_import_file before import_records when the user starts from a local CSV or spreadsheet export.',
  '- Use list_integration_channels before export_records when the user does not already know the destination channel_id.',
  '- Use connect_sanka when the user explicitly asks to connect or reconnect Sanka without retrying a protected action first.',
  '- If a protected tool reports missing authentication, call auth_status next so the tool result can surface reconnect metadata, then tell the user to approve the OAuth prompt and retry.',
  '- Individual HTTP requests to the API have a 30-second timeout. If a request times out, try a smaller query or add filters.',
  '- Code execution has a total timeout of approximately 5 minutes. If your code times out, simplify it or break it into smaller steps.',
].join('\n');

const DEFAULT_HOSTED_INSTRUCTIONS = [
  'This is the hosted Sanka MCP server used by packaged AI clients.',
  '',
  'Available tools:',
  '- connect_sanka: Start or resume the Sanka OAuth connection flow when the user explicitly asks to connect or reconnect Sanka.',
  '- auth_status: Debug whether the Sanka connector is authenticated. Do not use this as a preflight before protected Sanka tools.',
  '- list_private_messages: Review the authenticated user private inbox threads in Sanka.',
  '- sync_private_messages: Pull the latest private inbox threads into Sanka.',
  '- get_private_message_thread: Load one private inbox thread and its message history.',
  '- reply_private_message_thread: Send a reply on a private inbox thread.',
  '- archive_private_message_thread: Archive a private inbox thread.',
  '- list_companies: Search and review companies in Sanka.',
  '- get_company: Load one company in Sanka.',
  '- create_company: Create a company in Sanka.',
  '- update_company: Update a company in Sanka.',
  '- delete_company: Delete a company in Sanka.',
  '- get_company_price_table: Load company-level item pricing for one company.',
  '- update_company_price_table_company: Update the company-wide price-table mode or default company percentage.',
  '- update_company_price_table_item: Set or clear a company-specific price override for one item.',
  '- apply_company_price_table_items: Apply one company-level percentage override across all items for a company.',
  '- list_contacts: Search and review contacts in Sanka.',
  '- get_contact: Load one contact in Sanka.',
  '- create_contact: Create a contact in Sanka.',
  '- update_contact: Update a contact in Sanka.',
  '- delete_contact: Delete a contact in Sanka.',
  '- list_deals: Review deals (sales pipeline records) in Sanka.',
  '- get_deal: Load one deal in Sanka.',
  '- create_deal: Create a deal in Sanka.',
  '- update_deal: Update a deal in Sanka.',
  '- delete_deal: Delete a deal in Sanka.',
  '- list_deal_pipelines: List the deal pipelines and stages defined in the workspace.',
  '- list_items: Review items in Sanka.',
  '- get_item: Load one item in Sanka.',
  '- create_item: Create an item in Sanka.',
  '- update_item: Update an item in Sanka.',
  '- delete_item: Delete an item in Sanka.',
  '- list_orders: Search and review orders in Sanka.',
  '- get_order: Load one order in Sanka.',
  '- create_order: Create an order in Sanka.',
  '- update_order: Update an order in Sanka.',
  '- delete_order: Delete an order in Sanka.',
  '- list_purchase_orders: Review purchase orders in Sanka.',
  '- get_purchase_order: Load one purchase order in Sanka.',
  '- create_purchase_order: Create a purchase order in Sanka.',
  '- update_purchase_order: Update a purchase order in Sanka.',
  '- delete_purchase_order: Delete a purchase order in Sanka.',
  '- list_tasks: Search and review tasks in Sanka.',
  '- get_task: Load one task in Sanka.',
  '- create_task: Create a task in Sanka.',
  '- update_task: Update an existing task in Sanka.',
  '- delete_task: Delete a task in Sanka.',
  '- list_estimates: Review estimates in Sanka.',
  '- get_estimate: Load one estimate in Sanka.',
  '- download_estimate_pdf: Download one estimate as a PDF document.',
  '- create_estimate: Create an estimate in Sanka.',
  '- update_estimate: Update an estimate in Sanka.',
  '- delete_estimate: Delete an estimate in Sanka.',
  '- list_invoices: Review invoices in Sanka.',
  '- list_overdue_invoices: Review overdue invoices in Sanka that still have outstanding balance.',
  '- get_invoice: Load one invoice in Sanka.',
  '- download_invoice_pdf: Download one invoice as a PDF document.',
  '- list_payments: Review payments in Sanka.',
  '- get_payment: Load one payment in Sanka.',
  '- create_payment: Create a payment in Sanka.',
  '- update_payment: Update a payment in Sanka.',
  '- delete_payment: Delete a payment in Sanka.',
  '- download_payment_pdf: Download one payment as a PDF document.',
  '- list_slips: Review slips in Sanka.',
  '- get_slip: Load one slip in Sanka.',
  '- create_slip: Create a slip in Sanka.',
  '- update_slip: Update a slip in Sanka.',
  '- delete_slip: Delete a slip in Sanka.',
  '- download_slip_pdf: Download one slip as a PDF document.',
  '- list_bills: Review bills in Sanka.',
  '- get_bill: Load one bill in Sanka.',
  '- create_bill: Create a bill in Sanka.',
  '- update_bill: Update a bill in Sanka.',
  '- delete_bill: Delete a bill in Sanka.',
  '- list_disbursements: Review disbursements in Sanka.',
  '- get_disbursement: Load one disbursement in Sanka.',
  '- create_disbursement: Create a disbursement in Sanka.',
  '- update_disbursement: Update a disbursement in Sanka.',
  '- delete_disbursement: Delete a disbursement in Sanka.',
  '- download_order_pdf: Download one order as a PDF document.',
  '- create_invoice: Create an invoice in Sanka.',
  '- update_invoice: Update an invoice in Sanka.',
  '- delete_invoice: Delete an invoice in Sanka.',
  '- list_subscriptions: Review subscriptions in Sanka.',
  '- get_subscription: Load one subscription in Sanka.',
  '- create_subscription: Create a subscription in Sanka.',
  '- update_subscription: Update a subscription in Sanka.',
  '- delete_subscription: Delete a subscription in Sanka.',
  '- list_payments: Review payments in Sanka.',
  '- get_payment: Load one payment in Sanka.',
  '- create_payment: Create a payment in Sanka.',
  '- update_payment: Update a payment in Sanka.',
  '- delete_payment: Delete a payment in Sanka.',
  '- list_tickets: Review tickets in Sanka.',
  '- get_ticket: Load one ticket in Sanka.',
  '- create_ticket: Create a ticket in Sanka.',
  '- update_ticket: Update a ticket in Sanka.',
  '- delete_ticket: Delete a ticket in Sanka.',
  '- list_ticket_pipelines: List the ticket pipelines and stages defined in the workspace.',
  '- update_ticket_status: Update only the stage or status of a ticket in Sanka.',
  '- list_locations: Review locations in Sanka.',
  '- get_location: Load one location in Sanka.',
  '- create_location: Create a location in Sanka.',
  '- update_location: Update a location in Sanka.',
  '- delete_location: Delete a location in Sanka.',
  '- list_inventories: Review inventories in Sanka.',
  '- get_inventory: Load one inventory in Sanka.',
  '- create_inventory: Create an inventory record in Sanka.',
  '- update_inventory: Update an inventory record in Sanka.',
  '- delete_inventory: Delete an inventory record in Sanka.',
  '- list_inventory_transactions: Review inventory transactions in Sanka.',
  '- get_inventory_transaction: Load one inventory transaction in Sanka.',
  '- create_inventory_transaction: Create an inventory transaction in Sanka.',
  '- update_inventory_transaction: Update an inventory transaction in Sanka.',
  '- delete_inventory_transaction: Delete an inventory transaction in Sanka.',
  '- list_expenses: Review expense records in Sanka.',
  '- get_expense: Load one expense in Sanka.',
  '- upload_expense_attachment: Upload an expense attachment and return a file_id.',
  '- upload_import_file: Upload a CSV or similar import file and return a file_id.',
  '- import_records: Create a public import job from an uploaded file.',
  '- get_import_job: Load one import job by id.',
  '- list_import_jobs: List recent import jobs.',
  '- cancel_import_job: Cancel a running import job.',
  '- list_integration_channels: List connected export destinations and return channel ids.',
  '- export_records: Create a public export job for Sanka records.',
  '- get_export_job: Load one export job by id.',
  '- list_export_jobs: List recent export jobs.',
  '- cancel_export_job: Cancel a running export job.',
  '- create_expense: Create an expense in Sanka.',
  '- update_expense: Update an existing expense in Sanka.',
  '- delete_expense: Delete an expense in Sanka.',
  '- list_properties: Review object property definitions in Sanka.',
  '- get_property: Load one property definition in Sanka.',
  '- create_property: Create a custom property in Sanka.',
  '- update_property: Update a custom property in Sanka.',
  '- delete_property: Delete a custom property in Sanka.',
  '- get_calendar_bootstrap: Load the public calendar booking context for an event or attendance.',
  '- check_calendar_availability: Check available booking slots for a public calendar event.',
  '- create_calendar_attendance: Book a new public calendar attendance.',
  '- cancel_calendar_attendance: Cancel an existing public calendar attendance.',
  '- reschedule_calendar_attendance: Reschedule an existing public calendar attendance.',
  '- prospect_companies: Discover net-new companies from external sources using Sanka prospecting.',
  '- score_record: Score a company or deal in Sanka and explain the result.',
  '- generate_demo_workspace: Seed a workspace with curated demo CRM and billing data.',
  '- push_integration_sync: Emit outbound sync jobs for records to a connected integration channel.',
  '',
  'Guardrails:',
  '- Treat private message, company, contact, deal, item, order, purchase order, task, estimate, invoice, subscription, payment, slip, bill, disbursement, ticket, location, inventory, inventory transaction, expense, property, company pricing, calendar, prospecting, scoring, import, and export requests as live Sanka operations. Results and mutations must come from the dedicated MCP tools above.',
  '- If the user explicitly starts from the installed Sanka Plugin chip or names the Sanka Plugin, prefer the plugin-attached Sanka namespace in the current thread, usually `mcp__sanka_plugin__*`.',
  '- For private inbox messages, companies, contacts, deals, items, orders, purchase orders, tasks, estimates, invoices, overdue invoices, subscriptions, payments, slips, bills, disbursements, tickets, locations, inventories, inventory transactions, expenses, properties, company pricing, calendar workflows, prospecting, scoring, imports, or exports, call the matching protected tool directly without first calling auth_status or connect_sanka.',
  '- Protected Sanka tool calls are the OAuth trigger in clients like Codex, Claude, and Cursor.',
  '- Do not route plugin-scoped Sanka requests through stale global aliases such as `mcp__sanka_key__*`, `mcp__sanka__*`, or other duplicate global Sanka namespaces. Those can bypass the plugin attachment and surface raw auth errors.',
  '- If a protected tool is unavailable in the current client session, say the Sanka MCP server or plugin attachment is missing and ask the user to reconnect rather than guessing.',
  '- Never fabricate live Sanka data or substitute repo-local state, database access, or other out-of-band sources for dedicated Sanka tool results.',
  '',
  'Workflow:',
  '- Keep CRM queries narrow with search, pagination, workspace filters, or result limits when possible.',
  '- Use list_private_messages for the private account-level inbox. Do not confuse it with Sanka shared group inbox workflows.',
  '- Start reply flows with get_private_message_thread when you need the current thread history or reply target.',
  '- Use sync_private_messages before replying when the user asks for the latest state from Gmail or another connected private inbox channel.',
  '- Use get_company_price_table when the user asks for company-specific item pricing, and use search to narrow to one item when possible.',
  '- Keep item, subscription, payment, location, inventory, and inventory transaction queries narrow with workspace filters and local limits because those public endpoints return arrays.',
  '- Prefer list_deal_pipelines before describing deal stages so stage labels and ordering match the workspace configuration.',
  '- For orders, provide line items inside the nested `order` payload and prefer external references for linked companies or items when available.',
  '- For purchase orders, slips, bills, and disbursements, prefer linked company or contact ids/external references when the user already has those records in Sanka.',
  '- Prefer get_item before applying company price overrides when you need to confirm the default item price or item identity.',
  '- Use list_tasks or get_task before updating a task when the user wants to append to the current description, because task updates replace the field you send.',
  '- Prefer list_ticket_pipelines before moving tickets across stages so stage keys and labels match the workspace configuration.',
  '- Prefer list_properties or get_property before mutating object records when you need to confirm the current schema.',
  '- Start booking, rescheduling, or cancellation flows with get_calendar_bootstrap when you need the event context or existing attendance details.',
  '- Use check_calendar_availability before create_calendar_attendance or reschedule_calendar_attendance when the user needs the next available slot.',
  '- Prefer update_ticket_status over update_ticket when only the stage or status is changing.',
  '- Use prospect_companies when the user wants external company discovery or target-account research rather than only searching existing CRM records.',
  '- Use score_record when the user wants qualification, prioritization, or a transparent explanation of why a company or deal is strong or weak.',
  '- Use generate_demo_workspace when the user wants a fast sandbox or reproducible demo workspace with realistic lead-to-cash data.',
  '- Use push_integration_sync after a user edits or seeds records and explicitly wants those changes pushed to a connected downstream system.',
  '- Use upload_expense_attachment before create_expense or update_expense when the user wants a receipt or invoice attached.',
  '- upload_expense_attachment expects filename plus content_base64. Do not assume the hosted MCP server can read a client-local file path.',
  '- Use upload_import_file before import_records when the user starts from a local CSV or spreadsheet export.',
  '- Use list_integration_channels before export_records when the user does not already know the destination channel_id.',
  '- Use connect_sanka when the user explicitly asks to connect or reconnect Sanka without retrying a protected action first.',
  '- If a protected tool reports missing authentication, call auth_status next so the tool result can surface reconnect metadata, then tell the user to approve the OAuth prompt and retry.',
  '- Individual HTTP requests to the API have a 30-second timeout. If a request times out, try a smaller query or add filters.',
].join('\n');

interface InstructionsCacheEntry {
  fetchedInstructions: string;
  fetchedAt: number;
}

const instructionsCache = new Map<string, InstructionsCacheEntry>();

export async function getInstructions({
  customInstructionsPath,
  toolProfile = 'full',
}: {
  customInstructionsPath?: string | undefined;
  toolProfile?: ToolProfile | undefined;
}): Promise<string> {
  const now = Date.now();
  const cacheKey = `${customInstructionsPath ?? '__default__'}:${toolProfile}`;
  const cached = instructionsCache.get(cacheKey);

  if (cached && now - cached.fetchedAt <= INSTRUCTIONS_CACHE_TTL_MS) {
    return cached.fetchedInstructions;
  }

  // Evict stale entries so the cache doesn't grow unboundedly.
  for (const [key, entry] of instructionsCache) {
    if (now - entry.fetchedAt > INSTRUCTIONS_CACHE_TTL_MS) {
      instructionsCache.delete(key);
    }
  }

  let fetchedInstructions: string;

  if (customInstructionsPath) {
    fetchedInstructions = await fetchLatestInstructionsFromFile(customInstructionsPath);
  } else {
    fetchedInstructions = toolProfile === 'hosted' ? DEFAULT_HOSTED_INSTRUCTIONS : DEFAULT_FULL_INSTRUCTIONS;
  }

  instructionsCache.set(cacheKey, { fetchedInstructions, fetchedAt: now });
  return fetchedInstructions;
}

async function fetchLatestInstructionsFromFile(path: string): Promise<string> {
  try {
    return await fs.readFile(path, 'utf-8');
  } catch (error) {
    getLogger().error({ error, path }, 'Error fetching instructions from file');
    throw error;
  }
}
