// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import fs from 'fs/promises';
import { getLogger } from './logger';
import { ToolProfile } from './profile';

const INSTRUCTIONS_CACHE_TTL_MS = 15 * 60 * 1000; // 15 minutes
const DEFAULT_FULL_INSTRUCTIONS = [
  'This is the Sanka MCP server.',
  '',
  'Available tools:',
  '- connect_sanka: Start or resume the Sanka OAuth connection flow when the user explicitly asks to connect or reconnect Sanka.',
  '- search_docs: Search SDK documentation to find the right methods and parameters.',
  '- execute: Run TypeScript code against a pre-authenticated SDK client. Define an async run(client) function.',
  '- auth_status: Debug whether the Sanka connector is authenticated. Do not use this as a preflight before protected Sanka tools.',
  '- current_workspace: Show the currently authenticated Sanka workspace name, short code, and internal workspace_id.',
  '- list_workspaces: List workspaces available to this authenticated Sanka OAuth session.',
  '- switch_workspace: Switch this authenticated Sanka workspace by internal workspace_id from list_workspaces.',
  '- read_binary_download_chunk: Read one base64 chunk from a large PDF download returned by a PDF download tool.',
  '- list_private_messages: Review the authenticated user private inbox threads in Sanka.',
  '- sync_private_messages: Pull the latest private inbox threads into Sanka.',
  '- get_private_message_thread: Load one private inbox thread and its message history.',
  '- reply_private_message_thread: Send a reply on a private inbox thread.',
  '- archive_private_message_thread: Archive a private inbox thread.',
  '- query_records: Query records with server-side filters and field projection. Use this for filtered row requests instead of fetching full object lists; use scope=integration with provider=hubspot or provider=salesforce for live CRM-side rows; use object_type=custom_objects plus custom_object/custom_object_slug for Sanka custom object rows; use mode=dedupe_candidates for supported duplicate discovery previews.',
  '- aggregate_records: Count or group records with server-side filters. Use this for "how many" questions instead of paging through list_* tools; use scope=integration with provider=hubspot or provider=salesforce for live CRM-side counts; use object_type=custom_objects plus custom_object/custom_object_slug for Sanka custom object rows; use mode=dedupe_candidates to return supported duplicate candidate groups.',
  '- create_custom_object_record: Create a Sanka custom object row. Set custom_object or custom_object_slug to the custom object slug/internal key or id, and pass data using field names, internal_name values, or field UUIDs.',
  '- update_custom_object_record: Update a Sanka custom object row by row UUID. Pass data using field names, internal_name values, or field UUIDs.',
  '- archive_custom_object_record: Soft-archive a Sanka custom object row by row UUID.',
  '- list_associations: Review associations between Sanka records.',
  '- create_association: Create an association between two Sanka records using a workspace association label.',
  '- delete_association: Delete an association between two Sanka records.',
  '- list_companies: Search and review companies in Sanka.',
  '- get_company: Load one company in Sanka.',
  '- create_company: Create a company in Sanka.',
  '- update_company: Update a company in Sanka.',
  '- delete_company: Delete a company in Sanka.',
  '- get_company_price_table: Load company-level item pricing for one company.',
  '- update_company_price_table_company: Update the company-wide price-table mode or default company percentage.',
  '- update_company_price_table_item: Set or clear a company-specific price override for one item.',
  '- apply_company_price_table_items: Apply one company-level percentage override across all items for a company.',
  '- list_contacts: Search and review contacts in Sanka.',
  '- get_contact: Load one contact in Sanka.',
  '- create_contact: Create a contact in Sanka.',
  '- update_contact: Update a contact in Sanka.',
  '- delete_contact: Delete a contact in Sanka.',
  '- list_deals: Review deals. By default this lists Sanka pipeline records; use scope=integration with provider=hubspot or provider=salesforce for live CRM-side deals/opportunities.',
  '- get_deal: Load one deal in Sanka.',
  '- create_deal: Create a deal in Sanka.',
  '- update_deal: Update a deal in Sanka.',
  '- delete_deal: Delete a deal in Sanka.',
  '- list_deal_pipelines: List the deal pipelines and stages defined in the workspace.',
  '- resolve_record: Resolve an ambiguous company/deal/Salesforce Opportunity phrase to candidate Sanka or integration-backed records.',
  '- preview_workflow: Preview a supported workflow such as deal_to_estimate, deal_to_order, deal_to_subscription, estimate_to_invoice, order_to_invoice, order_to_subscription, subscription_to_invoice, order_to_purchase_order, deal_to_order_handoff, invoice_export, quote_readiness, revenue_control_summary, or sales_incentive_commission without writing records. For HubSpot Deal URLs, use source_system=hubspot and pass the URL as source_record.url. For Sanka Estimate billing, use workflow_type=estimate_to_invoice with source_record.object_type=estimate. For Sanka Subscription billing, use workflow_type=subscription_to_invoice with source_record.object_type=subscription and pass start_date/due_date when known. For HubSpot order or fulfillment handoffs, use workflow_type=deal_to_order_handoff with target_system=sanka. For HubSpot revenue summaries, use workflow_type=revenue_control_summary with source_system=hubspot, object_type=deal, a date range, and optional owner/customer filters. For sales incentive and commission drafts, use workflow_type=sales_incentive_commission with source_system=hubspot, object_type=deal, period/date range, optional owner/rep/customer filters, and compensation_rule_id or plan_id when needed. For freee sync previews, use workflow_type=invoice_export with source_system=sanka, object_type=invoice, target_system=freee, and an explicit sync_scope. For Salesforce Opportunity quote readiness, use source_system=salesforce, object_type=opportunity, and pass the Salesforce Opportunity id or URL. Direct CRM deal_to_invoice is intentionally unavailable; create or reuse a Sanka Order first.',
  '- start_workflow: Start a supported workflow such as deal_to_estimate, deal_to_order, deal_to_subscription, estimate_to_invoice, order_to_invoice, order_to_subscription, subscription_to_invoice, order_to_purchase_order, deal_to_order_handoff, or invoice_export, creating drafts, orders, subscriptions, invoices, purchase orders, approval requests, order handoff tasks, or explicitly scoped freee invoice draft syncs when needed. Do not use start_workflow for quote_readiness, revenue_control_summary, or sales_incentive_commission because they are read-only. Do not use deal_to_invoice for CRM deals or opportunities.',
  '- get_workflow_run: Load a workflow run, including created records, approval history, and audit events.',
  '- list_items: Review items in Sanka.',
  '- get_item: Load one item in Sanka.',
  '- create_item: Create an item in Sanka.',
  '- update_item: Update an item in Sanka.',
  '- delete_item: Delete an item in Sanka.',
  '- list_orders: Search and review orders in Sanka.',
  '- get_order: Load one order in Sanka.',
  '- upload_order_attachment: Upload an order attachment and return a file_id.',
  '- create_order: Create an order in Sanka.',
  '- update_order: Update an order in Sanka.',
  '- activate_order: Restore an archived order to active status in Sanka.',
  '- delete_order: Archive an order in Sanka. This is a soft delete, not a permanent delete.',
  '- permanent_delete_order: Permanently delete an already archived order in Sanka only when the user explicitly asks for permanent deletion and passes confirm=true.',
  '- list_purchase_orders: Review purchase orders in Sanka.',
  '- get_purchase_order: Load one purchase order in Sanka.',
  '- download_purchase_order_pdf: Download one purchase order as a PDF document.',
  '- upload_purchase_order_attachment: Upload a purchase order attachment and return a file_id.',
  '- create_purchase_order: Create a purchase order in Sanka.',
  '- update_purchase_order: Update a purchase order in Sanka.',
  '- delete_purchase_order: Delete a purchase order in Sanka.',
  '- list_tasks: Search and review tasks in Sanka.',
  '- get_task: Load one task in Sanka.',
  '- create_task: Create a task in Sanka.',
  '- update_task: Update an existing task in Sanka.',
  '- delete_task: Delete a task in Sanka.',
  '- list_estimates: Review estimates in Sanka.',
  '- get_estimate: Load one estimate in Sanka.',
  '- download_estimate_pdf: Download one estimate as a PDF document.',
  '- upload_estimate_attachment: Upload an estimate attachment and return a file_id.',
  '- create_estimate: Create an estimate in Sanka.',
  '- update_estimate: Update an estimate in Sanka.',
  '- delete_estimate: Delete an estimate in Sanka.',
  '- list_invoices: Review invoices in Sanka.',
  '- list_overdue_invoices: Review overdue invoices in Sanka that still have outstanding balance.',
  '- get_invoice: Load one invoice in Sanka.',
  '- download_invoice_pdf: Download one invoice as a PDF document.',
  '- send_invoice_email: Send or schedule an invoice PDF email from Sanka.',
  '- upload_invoice_attachment: Upload an invoice attachment and return a file_id.',
  '- list_payments: Review payments in Sanka.',
  '- get_payment: Load one payment in Sanka.',
  '- list_payment_allocations: Review invoice allocation rows for one payment in Sanka.',
  '- update_payment_allocations: Replace invoice allocation rows for one payment in Sanka.',
  '- create_payment: Create a payment in Sanka.',
  '- update_payment: Update a payment in Sanka.',
  '- delete_payment: Delete a payment in Sanka.',
  '- download_payment_pdf: Download one payment as a PDF document.',
  '- list_slips: Review slips in Sanka.',
  '- get_slip: Load one slip in Sanka.',
  '- create_slip: Create a slip in Sanka.',
  '- update_slip: Update a slip in Sanka.',
  '- delete_slip: Delete a slip in Sanka.',
  '- download_slip_pdf: Download one slip as a PDF document.',
  '- list_bills: Review bills in Sanka.',
  '- get_bill: Load one bill in Sanka.',
  '- upload_bill_attachment: Upload a bill attachment and return a file_id.',
  '- create_bill: Create a bill in Sanka.',
  '- update_bill: Update a bill in Sanka.',
  '- delete_bill: Delete a bill in Sanka.',
  '- list_disbursements: Review disbursements in Sanka.',
  '- get_disbursement: Load one disbursement in Sanka.',
  '- create_disbursement: Create a disbursement in Sanka.',
  '- update_disbursement: Update a disbursement in Sanka.',
  '- delete_disbursement: Delete a disbursement in Sanka.',
  '- list_disbursement_allocations: Review bill and expense payable allocation rows for one disbursement in Sanka.',
  '- create_disbursement_allocation: Add one bill or expense payable allocation row to a disbursement.',
  '- update_disbursement_allocation: Update one bill or expense payable allocation row on a disbursement.',
  '- delete_disbursement_allocation: Archive/delete one bill or expense payable allocation row from a disbursement.',
  '- download_order_pdf: Download one order as a PDF document.',
  '- create_invoice: Create an invoice in Sanka.',
  '- update_invoice: Update an invoice in Sanka.',
  '- activate_invoice: Restore an archived invoice to active usage status in Sanka.',
  '- delete_invoice: Archive an invoice in Sanka. This is a soft delete, not a permanent delete.',
  '- permanent_delete_invoice: Permanently delete an already archived invoice in Sanka only when the user explicitly asks for permanent deletion and passes confirm=true.',
  '- list_subscriptions: Review subscriptions in Sanka.',
  '- get_subscription: Load one subscription in Sanka.',
  '- create_subscription: Create a subscription in Sanka.',
  '- update_subscription: Update a subscription in Sanka.',
  '- delete_subscription: Delete a subscription in Sanka.',
  '- list_payments: Review payments in Sanka.',
  '- get_payment: Load one payment in Sanka.',
  '- list_payment_allocations: Review invoice allocation rows for one payment in Sanka.',
  '- update_payment_allocations: Replace invoice allocation rows for one payment in Sanka.',
  '- create_payment: Create a payment in Sanka.',
  '- update_payment: Update a payment in Sanka.',
  '- delete_payment: Delete a payment in Sanka.',
  '- list_tickets: Review tickets in Sanka.',
  '- get_ticket: Load one ticket in Sanka.',
  '- create_ticket: Create a ticket in Sanka.',
  '- update_ticket: Update a ticket in Sanka.',
  '- delete_ticket: Delete a ticket in Sanka.',
  '- list_ticket_pipelines: List the ticket pipelines and stages defined in the workspace.',
  '- update_ticket_status: Update only the stage or status of a ticket in Sanka.',
  '- list_locations: Review locations in Sanka.',
  '- get_location: Load one location in Sanka.',
  '- create_location: Create a location in Sanka.',
  '- update_location: Update a location in Sanka.',
  '- delete_location: Delete a location in Sanka.',
  '- list_inventories: Review inventories in Sanka.',
  '- get_inventory: Load one inventory in Sanka.',
  '- create_inventory: Create an inventory record in Sanka.',
  '- update_inventory: Update an inventory record in Sanka.',
  '- delete_inventory: Delete an inventory record in Sanka.',
  '- list_inventory_transactions: Review inventory transactions in Sanka.',
  '- get_inventory_transaction: Load one inventory transaction in Sanka.',
  '- create_inventory_transaction: Create an inventory transaction in Sanka.',
  '- update_inventory_transaction: Update an inventory transaction in Sanka.',
  '- delete_inventory_transaction: Delete an inventory transaction in Sanka.',
  '- list_expenses: Review expense records in Sanka.',
  '- get_expense: Load one expense in Sanka.',
  '- upload_expense_attachment: Upload an expense attachment and return a file_id.',
  '- list_employees: Review the Sanka employee directory and resolve worker_id values for HR workflows.',
  '- list_absences: Review leave and absence records in Sanka.',
  '- get_absence: Load one leave or absence record.',
  '- create_absence: Create a leave or absence request.',
  '- update_absence: Update an existing leave or absence record.',
  '- delete_absence: Archive/delete a leave or absence record.',
  '- list_attendance_records: Review employee attendance/time tracking records. Do not confuse this with public calendar attendance bookings.',
  '- get_attendance_record: Load one employee attendance/time tracking record.',
  '- create_attendance_record: Create an employee attendance/time tracking record.',
  '- update_attendance_record: Update an employee attendance/time tracking record.',
  '- delete_attendance_record: Archive/delete an employee attendance/time tracking record.',
  '- list_payroll_profiles: Review employee payroll profiles.',
  '- upsert_payroll_profile: Create or update an employee payroll profile.',
  '- list_payroll_runs: Review payroll runs.',
  '- get_payroll_run: Load one payroll run and employee calculation results.',
  '- download_payroll_payslip_pdf: Download payroll payslips as a PDF document.',
  '- calculate_payroll_run: Calculate a payroll run for a period.',
  '- create_payroll_journal_entry: Create or reuse one monthly Sanka Journal Entry from a payroll run.',
  '- approve_payroll_run: Approve a calculated payroll run after explicit user confirmation.',
  '- list_incentives: Review calculated incentive and commission records in Sanka.',
  '- list_incentive_plans: Review incentive and commission rules in Sanka.',
  '- list_incentive_company_options: Search company records for incentive rule source or payee ids.',
  '- create_incentive_plan: Create an incentive or partner commission rule in Sanka.',
  '- calculate_incentives: Preview or store incentive calculations for a period.',
  '- approve_incentives: Approve draft incentives after explicit user confirmation.',
  '- generate_incentive_payment_notice: Draft a partner payment request notice from calculated incentives.',
  '- upload_import_file: Upload a CSV or similar import file and return a file_id.',
  '- import_records: Create a public import job from an uploaded file.',
  '- get_import_job: Load one import job by id.',
  '- list_import_jobs: List recent import jobs.',
  '- cancel_import_job: Cancel a running import job.',
  '- list_integration_channels: List connected export destinations and return channel ids.',
  '- export_records: Create a public export job for Sanka records.',
  '- get_export_job: Load one export job by id.',
  '- list_export_jobs: List recent export jobs.',
  '- cancel_export_job: Cancel a running export job.',
  '- create_expense: Create an expense in Sanka.',
  '- update_expense: Update an existing expense in Sanka.',
  '- delete_expense: Delete an expense in Sanka.',
  '- list_properties: Review object property definitions in Sanka or a connected integration.',
  '- get_property: Load one property definition in Sanka or a connected integration.',
  '- create_property: Create a custom property in Sanka or a connected integration.',
  '- update_property: Update a custom property in Sanka or a connected integration.',
  '- delete_property: Delete a custom property in Sanka or a connected integration.',
  '- list_approval_rules / get_approval_rule_options / upsert_approval_rule / delete_approval_rule: Review and manage approval rules for a Sanka object. Pass object such as invoices, companies, contacts, deals, payments, estimates, or orders.',
  '- list_lock_rules / get_lock_rule_options / upsert_lock_rule / delete_lock_rule: Review and manage record lock rules for a Sanka object. Pass object; invoice lock rules can target full records, financial fields, or selected fields.',
  '- list_delivery_rules / get_delivery_rule_options / upsert_delivery_rule / delete_delivery_rule: Review and manage delivery rules. Delivery rules currently support invoices and control send/schedule readiness and required fields.',
  '- list_object_schemas: Review Sanka custom object schemas or connected HubSpot/Salesforce object schemas.',
  '- mutate_object_schema: Create, update, or delete Sanka/HubSpot/Salesforce custom object schemas through routed arguments.',
  '- list_journal_entries: Review Sanka journal entries or statement rows from a saved journal PL/BS/CF view.',
  '- create_journal_statement_view: Create a Sanka journal Profit and Loss, Balance Sheet, or Cash Flow saved view from existing journal entries.',
  '- list_views: List saved views for any supported Sanka object.',
  '- get_view: Load one saved view by id.',
  '- get_view_columns: Load resolved columns for one saved view.',
  '- create_view: Create a saved view for any supported Sanka object.',
  '- update_view: Update a saved view for any supported Sanka object.',
  '- delete_view: Delete a saved view.',
  '- list_reports: Review Sanka reports and dashboards.',
  '- get_report: Load one Sanka report or dashboard.',
  '- create_report: Create a Sanka report or dashboard with optional panels.',
  '- update_report: Update a Sanka report or dashboard.',
  '- delete_report: Delete a Sanka report or dashboard.',
  '- get_calendar_bootstrap: Load the public calendar booking context for an event or attendance.',
  '- check_calendar_availability: Check available booking slots for a public calendar event.',
  '- create_calendar_attendance: Book a new public calendar attendance.',
  '- cancel_calendar_attendance: Cancel an existing public calendar attendance.',
  '- reschedule_calendar_attendance: Reschedule an existing public calendar attendance.',
  '- prospect_companies: Discover net-new companies from external sources using Sanka prospecting.',
  '- score_record: Score a company or deal in Sanka and explain the result.',
  '- generate_demo_workspace: Seed a workspace with curated demo CRM and billing data, or create demo records directly in HubSpot/Salesforce with target=integration after dry_run.',
  '- push_integration_sync: Emit outbound sync jobs for records to a connected integration channel.',
  '- browser_use: Run an allowlisted browser automation workflow through the governed Sanka browser-use layer, starting with demo.hubspot.company_avatar for HubSpot demo company avatars.',
  '',
  'Guardrails:',
  '- Treat private message, association, company, contact, deal, workflow run, item, order, purchase order, task, estimate, invoice, subscription, payment, slip, bill, disbursement, ticket, location, inventory, inventory transaction, custom object record, journal entry, saved view, report, expense, employee, absence, attendance record, payroll profile, payroll run, incentive, property, company pricing, calendar, prospecting, scoring, import, and export requests as live Sanka operations. Results and mutations must come from the dedicated MCP tools above.',
  '- If the user explicitly starts from the installed Sanka Plugin chip or names the Sanka Plugin, prefer the plugin-attached Sanka namespace in the current thread, usually `mcp__sanka_plugin__*`.',
  '- For private inbox messages, associations, companies, contacts, deals, workflow runs, items, orders, purchase orders, tasks, estimates, invoices, overdue invoices, subscriptions, payments, slips, bills, disbursements, tickets, locations, inventories, inventory transactions, custom object records, expenses, employees, absences, attendance records, payroll profiles, payroll runs, incentives, properties, company pricing, calendar workflows, prospecting, scoring, imports, or exports, call the matching protected tool directly without first calling auth_status or connect_sanka.',
  '- Native OAuth clients such as Codex and Claude should use the MCP OAuth challenge surfaced during connection or protected tool calls. Other clients may receive a Connect Sanka URL fallback from protected tool results.',
  '- Do not route plugin-scoped Sanka requests through stale global aliases such as `mcp__sanka_key__*`, `mcp__sanka__*`, or other duplicate global Sanka namespaces. Those can bypass the plugin attachment and surface raw auth errors.',
  '- The workspace_id parameter on data tools is not a workspace switcher. It expects the authenticated workspace internal UUID, not the short numeric workspace code shown in Sanka URLs. Usually omit workspace_id; use current_workspace, list_workspaces, and switch_workspace for workspace context or switching.',
  '- Do not render Sanka record numbers as Markdown issue references with a leading hash, for example hash followed by 7. Use safe labels such as "Invoice No. 7", "売上請求番号 7", or the UUID instead.',
  '- For Japanese user-facing replies, use Sanka object names precisely: Order is "受注" and Invoice is "売上請求". Do not translate them as "注文" or "請求書" unless quoting external source text.',
  '- For Japanese user-facing tables, show display labels for internal statuses. For example, status=draft should be shown as "下書き"; include the raw key only when explicitly useful, such as "下書き（draft）".',
  '- Do not say a Sanka tool or API call failed unless the tool result is isError or the structuredContent explicitly contains an error or HTTP status >= 400. If a later tool call succeeds, report the successful state.',
  '- Do not use search_docs or execute as a fallback for live private inbox, association, company, contact, deal, workflow run, item, order, purchase order, task, estimate, invoice, overdue invoice, subscription, payment, slip, bill, disbursement, ticket, location, inventory, inventory transaction, custom object record, expense, employee, absence, attendance record, payroll profile, payroll run, incentive, property, company pricing, calendar, prospecting, scoring, import, or export work when a dedicated MCP tool covers the request.',
  '- If a protected tool is unavailable in the current client session, say the Sanka MCP server or plugin attachment is missing and ask the user to reconnect rather than guessing.',
  '- Never fabricate live Sanka data or substitute repo-local state, database access, or other out-of-band sources for dedicated Sanka tool results.',
  '',
  'Workflow:',
  '- Use search_docs before writing code when you need to discover the right SDK method or parameter shape for uncovered workflows.',
  '- Use execute only for Sanka SDK workflows that are not covered by dedicated MCP tools.',
  '- Keep CRM queries narrow with search, pagination, workspace filters, or result limits when possible.',
  '- For integration-side company/contact/deal counts or lists, use aggregate_records, list_companies, list_contacts, or list_deals with scope=integration, provider=hubspot or provider=salesforce, and channel_id when multiple channels exist. HubSpot deals map to deals; Salesforce opportunities map to deals. For Sanka custom object rows, use query_records or aggregate_records with scope=sanka, object_type=custom_objects, and custom_object/custom_object_slug set to the custom object slug/internal key or id; display names are accepted as a fallback. Use create_custom_object_record, update_custom_object_record, or archive_custom_object_record for row mutations.',
  '- For record association work, use list_associations, create_association, and delete_association. There is no update_association tool; changing an association label should be handled as delete_association followed by create_association so the API can re-check label constraints.',
  '- For date- or stage-filtered integration deals, pass filters to list_deals or query_records instead of fetching all rows. The Sanka API accepts common aliases such as stage/dealstage/StageName and closed_at/closedate/CloseDate for HubSpot and Salesforce deal fields.',
  '- For duplicate discovery, use aggregate_records or query_records with mode=dedupe_candidates, match_fields such as ["name"] or ["email"], and a bounded scan_limit before any delete or dedupe mutation.',
  '- For Sanka orders and invoices, delete_order and delete_invoice are soft archive operations. Describe the result as archived / アーカイブ済み, not permanently deleted. Use permanent_delete_order or permanent_delete_invoice only when the user explicitly asks for permanent deletion, the record is already archived, and confirm=true is provided.',
  '- For integration-side HubSpot company create/update/delete/dedupe, use the existing create_company, update_company, or delete_company tools with target=integration or target=both. Salesforce integration records are read-only in these tools for now. Run dry_run=true first for Sanka or remote delete and dedupe, inspect sanka_action/warnings/sync_state, and set confirm=true only after the user explicitly approves the destructive action.',
  '- For integration-side HubSpot/Salesforce property schemas, use list_properties or get_property with scope=integration, provider=hubspot or provider=salesforce, and channel_id when multiple channels exist. HubSpot deals map to deals; Salesforce opportunities map to deals.',
  '- For remote property create/update/delete, use create_property, update_property, or delete_property with target=integration or target=both. Run dry_run=true first for remote property writes, and set confirm=true only after the user explicitly approves a delete. Salesforce property writes are limited to custom fields ending in __c.',
  '- For Sanka company cycles, billing_cycle and payment_cycle are standard company fields, not a custom-property creation flow. Set them directly with create_company/update_company top-level inputs: billing_cycle="end" for 月末締め or "1" through "31" for a closing day; payment_cycle="nmonth_end" for 翌月末払い, "cmonth_end" for 当月末払い, or net terms such as "net_30". If the user only says "月末" for payment cycle, ask whether they mean current-month end or next-month end.',
  '- For custom object schema management, use list_object_schemas and mutate_object_schema with scope/target=sanka|integration|both. HubSpot schema writes use HubSpot object schema APIs; Salesforce schema writes use Metadata API. Always run dry_run=true first, and require confirm=true for deletes.',
  '- For rule settings, use approval-rules, lock-rules, and delivery-rules tools with object rather than object-specific endpoints. Use approval rules when an action must wait for approval; use lock rules when a matching record should not be edited; use delivery rules when invoice send/schedule readiness or required fields should change. Delivery rules are invoice-only for now.',
  '- For journal-backed P&L, balance sheet, or cash-flow requests, use create_journal_statement_view first to create the saved view, then use list_journal_entries with the returned view_id when you need to read the generated statement rows.',
  '- For normal saved view requests, use create_view/list_views/get_view/get_view_columns/update_view/delete_view instead of object-specific workarounds. Pass object names such as orders, invoices, companies, contacts, deals, tickets, tasks, custom_object, dashboards, or panels.',
  '- For report/dashboard creation, use create_report. Use list_reports/get_report to inspect reports before updates or deletes.',
  '- Use list_private_messages for the private account-level inbox. Do not confuse it with Sanka shared group inbox workflows.',
  '- Start reply flows with get_private_message_thread when you need the current thread history or reply target.',
  '- Use sync_private_messages before replying when the user asks for the latest state from Gmail or another connected private inbox channel.',
  '- Use get_company_price_table when the user asks for company-specific item pricing, and use search to narrow to one item when possible.',
  '- For create_subscription, use exactly one customer identifier: contact_id, company_id, or customer_id. Company-only customers are valid. When converting invoice or order lines, fetch the source record first and pass line_items/items with item_id when present, or name plus amount/quantity and price/unit_price when no linked item_id exists.',
  '- For leave requests such as vacation, PTO, sick leave, or absences, use create_absence/list_absences/get_absence/update_absence/delete_absence rather than tasks or calendar bookings.',
  '- For employee work attendance and time tracking, use list_attendance_records/get_attendance_record/create_attendance_record/update_attendance_record/delete_attendance_record; reserve create_calendar_attendance for public event booking only.',
  '- For payroll setup and calculations, use list_payroll_profiles/upsert_payroll_profile and list_payroll_runs/get_payroll_run/calculate_payroll_run. Use create_payroll_journal_entry when the user wants a monthly payroll run posted to Sanka Journal Entries. Use download_payroll_payslip_pdf when the user explicitly asks for payroll payslip PDFs. Use approve_payroll_run only after explicit user confirmation.',
  '- Keep item, subscription, payment, location, inventory, and inventory transaction queries narrow with workspace filters and local limits because those public endpoints return arrays.',
  '- Prefer list_deal_pipelines before describing deal stages so stage labels and ordering match the workspace configuration.',
  '- Use get_estimate for normal estimate lookups. Only use download_estimate_pdf when the user explicitly asks for a PDF, file, attachment, download, or rendered PDF inspection.',
  '- For Sanka object URL requests, call the matching get_* tool when needed and return app_url from the object payload or workflow-created record result. Do not ask the user to copy the URL from the Sanka UI when app_url is present.',
  '- PDF download tools return download_complete=true plus content_base64 for small files. For large files, download_complete=false and content_base64_available=false; this is not a completed user download. If download_url is present, fetch that URL directly and attach or save the PDF before telling the user the download is complete. Only call read_binary_download_chunk when download_url is absent or the direct download fails; then concatenate content_base64 chunks in order, decode the combined base64 string, and attach or save the decoded PDF. Do not call resources/read for resource://tool-response.',
  '- For invoice email sending, use send_invoice_email rather than changing invoice status. For scheduled sends, pass action="schedule" and scheduled_at as an ISO datetime in the user/workspace timezone.',
  '- If a PDF download returns 404 after the record was visible earlier, verify current_workspace/list_workspaces and use switch_workspace with the internal workspace UUID before retrying. Record numbers and UUID lookups are workspace-context dependent; do not retry numeric IDs in a different workspace as if they were globally safe.',
  '- For subscription record edits such as start date, end date, status, or linked contract changes, use update_subscription directly. Pass start_date/end_date as ISO dates and contract_id or contract_ids for Sanka Contract associations; pass an empty contract_ids array only when the user explicitly wants to clear linked contracts.',
  '- For lead-to-cash workflow requests like creating or previewing an estimate from a deal, use preview_workflow directly when the user gives a HubSpot Deal URL; pass workflow_type=deal_to_estimate, source_record.source_system=hubspot, object_type=deal, and source_record.url. Do not ask the user to explain Sanka sync behavior. The API will use a synced Sanka deal if available, otherwise use authorized HubSpot access for read-only preview and supported execution. Use resolve_record only when the source phrase is ambiguous and no URL/id is present. Use start_workflow to create the estimate draft and approval request only after explicit user confirmation, and get_workflow_run for status.',
  '- For CRM-origin invoice requests such as "create an invoice from this HubSpot Deal" or Salesforce Opportunity billing, do not call deal_to_invoice or create_invoice directly from the CRM record. Preview the source with workflow_type=deal_to_order, tell the user that Sanka will first create or reuse a Sanka Order so billing can be generated correctly, ask for explicit confirmation, then start_workflow with workflow_type=deal_to_order. Create invoices only from the resulting Sanka Order with workflow_type=order_to_invoice. freee sync is a separate invoice_export workflow step; after creating invoices from Orders, preview invoice_export with sync_scope=created_in_workflow_run or selected_invoice_ids, then start invoice_export only after explicit user approval.',
  '- For Sanka Estimate invoice requests such as "create an invoice from this estimate", use workflow_type=estimate_to_invoice with source_record.source_system=sanka, object_type=estimate, and the Sanka Estimate id. Explain that Sanka will create or reuse a Sanka Order from the Estimate before creating the Invoice.',
  '- For CRM-origin subscription requests such as "create subscriptions from HubSpot Deals" or "bulk-create subscriptions from deals with a subscription flag", use workflow_type=deal_to_subscription. For HubSpot batch lists, pass source_record.source_system=hubspot, object_type=deal, portal_id or channel_id, and options such as subscription_flag_property plus subscription_flag_value or subscription_flag_values. Preview first, explain that Sanka will create or reuse Orders before creating Subscriptions, then start only after explicit confirmation.',
  '- For Sanka Subscription invoice requests such as "create invoices from these subscriptions", use workflow_type=subscription_to_invoice with source_record.source_system=sanka, object_type=subscription, and one record_id or options.subscription_ids for a batch. Pass start_date and due_date when the user gives the target billing period or payment terms. Preview first when the scope is broad or ambiguous.',
  '- For CRM-origin procurement requests such as "if this HubSpot Deal lacks inventory, create a purchase order", do not create a purchase order directly from the CRM deal/opportunity. First route the CRM record through deal_to_order, explain that Sanka will create or reuse the Sanka Order first, ask for explicit confirmation, then use workflow_type=order_to_purchase_order with the resulting Sanka Order. order_to_purchase_order previews shortage lines and creates purchase orders only for detected inventory shortages.',
  '- For Disbursement to Expense or Bill payable links, use list_disbursement_allocations/create_disbursement_allocation/update_disbursement_allocation/delete_disbursement_allocation. Do not use generic association tools for Expense <> Disbursement because that relationship is DisbursementPayableAllocation-backed.',
  '- For HubSpot order or fulfillment handoff requests such as "move this HubSpot deal to order processing", "create an order draft from this HubSpot Deal", "preview fulfillment handoff", or "check inventory and delivery timing", call preview_workflow with workflow_type=deal_to_order_handoff, source_record.source_system=hubspot, object_type=deal, and the HubSpot Deal id or URL. Summarize customer/contact resolution, line items, inventory availability, shortages, lead-time and delivery timing, duplicate order or handoff warnings, blockers, and required_confirmation. Missing inventory or lead-time data is a limitation to report, not a reason to invent data. Call start_workflow only after explicit confirmation; pass a stable idempotency_key and allow_duplicate_order only when the user explicitly approved another order. HubSpot writeback happens only after successful Sanka order or handoff creation.',
  '- For freee invoice draft sync requests, use preview_workflow with workflow_type=invoice_export, source_record.source_system=sanka, source_record.object_type=invoice, options.target_system=freee, and an explicit sync_scope. Prefer created_in_workflow_run after an order_to_invoice run or selected_invoice_ids for user-selected invoices. If the user only says to sync Sanka invoices to freee invoice drafts without a scope, do not call start_workflow; preview returns needs_confirmation with options, or ask the user to choose. all_eligible_unsynced requires confirm_all=true and explicit user confirmation. Re-sync or multiple freee drafts require allow_resync or allow_multiple_freee_drafts plus user intent.',
  '- For HubSpot revenue control questions such as "summarize this month\'s HubSpot revenue", "show unbilled deals", "show approval waits", "show unpaid invoices", or "what revenue is blocked?", call preview_workflow with workflow_type=revenue_control_summary, source_record.source_system=hubspot, object_type=deal, and options for start_date/end_date or date_range. Summarize won, quote_drafted, approval_pending, unbilled, invoiced, unpaid, blocked, totals by currency/owner/customer/aging, top_blockers, and next_actions. This is read-only; do not call start_workflow or mutate HubSpot, Sanka, freee, or Stripe records. For sales incentive or commission questions such as "calculate April commissions", "calculate this month sales incentives by rep", "show draft commissions", or "flag unpaid or low-margin deals", call preview_workflow with workflow_type=sales_incentive_commission, source_record.source_system=hubspot, object_type=deal, and options for period/date range, channel_id, CRM owner/rep/customer filters, include_records/include_excluded, include_payment_status, include_margin, include_refunds, and compensation_rule_id or plan_id when needed. Summarize total reps, included/excluded/flagged deals, eligible and commission totals by currency, rule version/snapshot, rep summaries, deal explanations, unpaid/refund/low-margin/unmapped exceptions, warnings, and suggested next actions. This is draft/read-only; do not call start_workflow or mutate HubSpot, Salesforce, Sanka invoices/orders/payments, freee, Stripe, platform mappings, compensation rules, payouts, or approvals.',
  '- For Salesforce quote-readiness questions such as "Can this Salesforce Opportunity be quoted?", call preview_workflow with workflow_type=quote_readiness, source_record.source_system=salesforce, object_type=opportunity, and the Salesforce Opportunity id or URL. The tool routes this read-only CPQ business preview through Sanka quote-readiness routes where Salesforce is the source platform. Summarize ready, target_record, financials, line item checks, approval, hard_blockers, warnings, suggested_fixes, source_records, sanka_records, and orchestration_plan. Do not call Salesforce-specific all-in-one create tools; compose generic Sanka search/create/estimate/workflow tools only when a later create flow is explicitly supported and requested.',
  '- For orders, provide line items inside the nested `order` payload and prefer external references for linked companies or items when available.',
  '- For purchase orders, slips, bills, and disbursements, prefer linked company or contact ids/external references when the user already has those records in Sanka.',
  '- Prefer get_item before applying company price overrides when you need to confirm the default item price or item identity.',
  '- Use list_tasks or get_task before updating a task when the user wants to append to the current description, because task updates replace the field you send.',
  '- Prefer list_ticket_pipelines before moving tickets across stages so stage keys and labels match the workspace configuration.',
  '- Prefer list_properties or get_property before mutating object records or property definitions when you need to confirm the current schema.',
  '- Start booking, rescheduling, or cancellation flows with get_calendar_bootstrap when you need the event context or existing attendance details.',
  '- Use check_calendar_availability before create_calendar_attendance or reschedule_calendar_attendance when the user needs the next available slot.',
  '- Prefer update_ticket_status over update_ticket when only the stage or status is changing.',
  '- Use prospect_companies when the user wants external company discovery or target-account research rather than only searching existing CRM records.',
  '- Use score_record when the user wants qualification, prioritization, or a transparent explanation of why a company or deal is strong or weak.',
  '- Use generate_demo_workspace when the user wants a fast sandbox or reproducible demo workspace with realistic lead-to-cash data. For direct HubSpot/Salesforce demo creation, call it with target=integration, provider, dry_run=true first, then confirm=true only after explicit approval. For provider custom object demo records, pass custom_objects with external_object_type and records or count/name_property; the custom object schema must already exist.',
  '- Use push_integration_sync after a user edits or seeds records and explicitly wants those changes pushed to a connected downstream system.',
  '- Use browser_use only for registered browser workflows when a third-party API cannot perform the requested operation. For HubSpot demo company avatars, use workflow="demo.hubspot.company_avatar", driver="agent_browser", dry_run=true first, then run with dry_run=false and confirm=true only after the dry run is reviewed. Do not use browser_use for open-ended browsing or arbitrary web instructions.',
  '- HubSpot company avatar note: hs_logo_url can be updated by API but does not control the visible round record/list avatar. The visible avatar is backed by HubSpot-managed state such as hs_avatar_filemanager_key, which is read-only through public CRM property updates, so demo avatar updates must go through the registered browser workflow or be left as default HubSpot icons.',
  '- When a create tool returns a governance advisory such as missing_recommended_partner, report that the record was created and ask for explicit permission before creating or linking a company/contact.',
  '- Use upload_expense_attachment before create_expense or update_expense when the user wants a receipt or invoice attached.',
  '- upload_expense_attachment expects filename plus content_base64. Do not assume the hosted MCP server can read a client-local file path.',
  '- Use upload_bill_attachment before create_bill or update_bill when the user wants a bill file attached.',
  '- upload_bill_attachment expects filename plus content_base64. Do not assume the hosted MCP server can read a client-local file path.',
  '- Use list_employees to resolve the full employee directory. Do not infer employees from absences, attendance records, or payroll profiles because those only show employees with related HR records.',
  '- Use upload_order_attachment, upload_purchase_order_attachment, upload_estimate_attachment, or upload_invoice_attachment before the matching create/update tool when the user wants a file attached.',
  '- Document attachment upload tools expect filename plus content_base64. Do not assume the hosted MCP server can read a client-local file path.',
  '- For partner commissions, resolve the partner company id with list_incentive_company_options or list_companies, create an invoice_paid company-payee rule with create_incentive_plan, run calculate_incentives with dry_run=true first, then set dry_run=false only when the user wants draft incentives stored. Use approve_incentives only after explicit approval.',
  '- Use generate_incentive_payment_notice when the user asks for a partner payment request or invoice-request notice from calculated incentives.',
  '- Use upload_import_file before import_records when the user starts from a local CSV or spreadsheet export.',
  '- Use list_integration_channels before export_records when the user does not already know the destination channel_id.',
  '- Use connect_sanka when the user explicitly asks to connect or reconnect Sanka without retrying a protected action first.',
  '- If a protected tool reports missing authentication and structuredContent.required_user_facing_reply is present, include that field verbatim in the next visible response before stopping; it contains the exact full Connect Sanka URL. Do not omit the URL, hide it behind a short label like "Connect Sanka", abbreviate the token, replace it with "...", or only tell the user to reconnect. If the field is missing, call auth_status so the tool result can surface reconnect metadata. Do not fabricate login URLs. Then tell the user to retry after reconnecting.',
  '- Individual HTTP requests to the API have a 30-second timeout. If a request times out, try a smaller query or add filters.',
  '- Code execution has a total timeout of approximately 5 minutes. If your code times out, simplify it or break it into smaller steps.',
].join('\n');

const DEFAULT_HOSTED_INSTRUCTIONS = [
  'This is the hosted Sanka MCP server used by packaged AI clients.',
  '',
  'Available tools:',
  '- connect_sanka: Start or resume the Sanka OAuth connection flow when the user explicitly asks to connect or reconnect Sanka.',
  '- auth_status: Debug whether the Sanka connector is authenticated. Do not use this as a preflight before protected Sanka tools.',
  '- current_workspace: Show the currently authenticated Sanka workspace name, short code, and internal workspace_id.',
  '- list_workspaces: List workspaces available to this authenticated Sanka OAuth session.',
  '- switch_workspace: Switch this authenticated Sanka workspace by internal workspace_id from list_workspaces.',
  '- read_binary_download_chunk: Read one base64 chunk from a large PDF download returned by a PDF download tool.',
  '- list_private_messages: Review the authenticated user private inbox threads in Sanka.',
  '- sync_private_messages: Pull the latest private inbox threads into Sanka.',
  '- get_private_message_thread: Load one private inbox thread and its message history.',
  '- reply_private_message_thread: Send a reply on a private inbox thread.',
  '- archive_private_message_thread: Archive a private inbox thread.',
  '- query_records: Query records with server-side filters and field projection. Use this for filtered row requests instead of fetching full object lists; use scope=integration with provider=hubspot or provider=salesforce for live CRM-side rows; use object_type=custom_objects plus custom_object/custom_object_slug for Sanka custom object rows; use mode=dedupe_candidates for supported duplicate discovery previews.',
  '- aggregate_records: Count or group records with server-side filters. Use this for "how many" questions instead of paging through list_* tools; use scope=integration with provider=hubspot or provider=salesforce for live CRM-side counts; use object_type=custom_objects plus custom_object/custom_object_slug for Sanka custom object rows; use mode=dedupe_candidates to return supported duplicate candidate groups.',
  '- create_custom_object_record: Create a Sanka custom object row. Set custom_object or custom_object_slug to the custom object slug/internal key or id, and pass data using field names, internal_name values, or field UUIDs.',
  '- update_custom_object_record: Update a Sanka custom object row by row UUID. Pass data using field names, internal_name values, or field UUIDs.',
  '- archive_custom_object_record: Soft-archive a Sanka custom object row by row UUID.',
  '- list_associations: Review associations between Sanka records.',
  '- create_association: Create an association between two Sanka records using a workspace association label.',
  '- delete_association: Delete an association between two Sanka records.',
  '- list_companies: Search and review companies in Sanka.',
  '- get_company: Load one company in Sanka.',
  '- create_company: Create a company in Sanka.',
  '- update_company: Update a company in Sanka.',
  '- delete_company: Delete a company in Sanka.',
  '- get_company_price_table: Load company-level item pricing for one company.',
  '- update_company_price_table_company: Update the company-wide price-table mode or default company percentage.',
  '- update_company_price_table_item: Set or clear a company-specific price override for one item.',
  '- apply_company_price_table_items: Apply one company-level percentage override across all items for a company.',
  '- list_contacts: Search and review contacts in Sanka.',
  '- get_contact: Load one contact in Sanka.',
  '- create_contact: Create a contact in Sanka.',
  '- update_contact: Update a contact in Sanka.',
  '- delete_contact: Delete a contact in Sanka.',
  '- list_deals: Review deals. By default this lists Sanka pipeline records; use scope=integration with provider=hubspot or provider=salesforce for live CRM-side deals/opportunities.',
  '- get_deal: Load one deal in Sanka.',
  '- create_deal: Create a deal in Sanka.',
  '- update_deal: Update a deal in Sanka.',
  '- delete_deal: Delete a deal in Sanka.',
  '- list_deal_pipelines: List the deal pipelines and stages defined in the workspace.',
  '- resolve_record: Resolve an ambiguous company/deal/Salesforce Opportunity phrase to candidate Sanka or integration-backed records.',
  '- preview_workflow: Preview a supported workflow such as deal_to_estimate, deal_to_order, deal_to_subscription, estimate_to_invoice, order_to_invoice, order_to_subscription, subscription_to_invoice, order_to_purchase_order, deal_to_order_handoff, invoice_export, quote_readiness, revenue_control_summary, or sales_incentive_commission without writing records. For HubSpot Deal URLs, use source_system=hubspot and pass the URL as source_record.url. For Sanka Estimate billing, use workflow_type=estimate_to_invoice with source_record.object_type=estimate. For Sanka Subscription billing, use workflow_type=subscription_to_invoice with source_record.object_type=subscription and pass start_date/due_date when known. For HubSpot order or fulfillment handoffs, use workflow_type=deal_to_order_handoff with target_system=sanka. For HubSpot revenue summaries, use workflow_type=revenue_control_summary with source_system=hubspot, object_type=deal, a date range, and optional owner/customer filters. For sales incentive and commission drafts, use workflow_type=sales_incentive_commission with source_system=hubspot, object_type=deal, period/date range, optional owner/rep/customer filters, and compensation_rule_id or plan_id when needed. For freee sync previews, use workflow_type=invoice_export with source_system=sanka, object_type=invoice, target_system=freee, and an explicit sync_scope. For Salesforce Opportunity quote readiness, use source_system=salesforce, object_type=opportunity, and pass the Salesforce Opportunity id or URL.',
  '- start_workflow: Start a supported workflow such as deal_to_estimate, deal_to_order, deal_to_subscription, estimate_to_invoice, order_to_invoice, order_to_subscription, subscription_to_invoice, order_to_purchase_order, deal_to_order_handoff, or invoice_export, creating drafts, orders, subscriptions, invoices, purchase orders, approval requests, order handoff tasks, or explicitly scoped freee invoice draft syncs when needed. Do not use deal_to_invoice for CRM deals or opportunities. Do not use start_workflow for quote_readiness, revenue_control_summary, or sales_incentive_commission because they are read-only.',
  '- get_workflow_run: Load a workflow run, including created records, approval history, and audit events.',
  '- list_items: Review items in Sanka.',
  '- get_item: Load one item in Sanka.',
  '- create_item: Create an item in Sanka.',
  '- update_item: Update an item in Sanka.',
  '- delete_item: Delete an item in Sanka.',
  '- list_orders: Search and review orders in Sanka.',
  '- get_order: Load one order in Sanka.',
  '- upload_order_attachment: Upload an order attachment and return a file_id.',
  '- create_order: Create an order in Sanka.',
  '- update_order: Update an order in Sanka.',
  '- activate_order: Restore an archived order to active status in Sanka.',
  '- delete_order: Archive an order in Sanka. This is a soft delete, not a permanent delete.',
  '- permanent_delete_order: Permanently delete an already archived order in Sanka only when the user explicitly asks for permanent deletion and passes confirm=true.',
  '- list_purchase_orders: Review purchase orders in Sanka.',
  '- get_purchase_order: Load one purchase order in Sanka.',
  '- download_purchase_order_pdf: Download one purchase order as a PDF document.',
  '- upload_purchase_order_attachment: Upload a purchase order attachment and return a file_id.',
  '- create_purchase_order: Create a purchase order in Sanka.',
  '- update_purchase_order: Update a purchase order in Sanka.',
  '- delete_purchase_order: Delete a purchase order in Sanka.',
  '- list_tasks: Search and review tasks in Sanka.',
  '- get_task: Load one task in Sanka.',
  '- create_task: Create a task in Sanka.',
  '- update_task: Update an existing task in Sanka.',
  '- delete_task: Delete a task in Sanka.',
  '- list_estimates: Review estimates in Sanka.',
  '- get_estimate: Load one estimate in Sanka.',
  '- download_estimate_pdf: Download one estimate as a PDF document.',
  '- upload_estimate_attachment: Upload an estimate attachment and return a file_id.',
  '- create_estimate: Create an estimate in Sanka.',
  '- update_estimate: Update an estimate in Sanka.',
  '- delete_estimate: Delete an estimate in Sanka.',
  '- list_invoices: Review invoices in Sanka.',
  '- list_overdue_invoices: Review overdue invoices in Sanka that still have outstanding balance.',
  '- get_invoice: Load one invoice in Sanka.',
  '- download_invoice_pdf: Download one invoice as a PDF document.',
  '- send_invoice_email: Send or schedule an invoice PDF email from Sanka.',
  '- upload_invoice_attachment: Upload an invoice attachment and return a file_id.',
  '- list_payments: Review payments in Sanka.',
  '- get_payment: Load one payment in Sanka.',
  '- list_payment_allocations: Review invoice allocation rows for one payment in Sanka.',
  '- update_payment_allocations: Replace invoice allocation rows for one payment in Sanka.',
  '- create_payment: Create a payment in Sanka.',
  '- update_payment: Update a payment in Sanka.',
  '- delete_payment: Delete a payment in Sanka.',
  '- download_payment_pdf: Download one payment as a PDF document.',
  '- list_slips: Review slips in Sanka.',
  '- get_slip: Load one slip in Sanka.',
  '- create_slip: Create a slip in Sanka.',
  '- update_slip: Update a slip in Sanka.',
  '- delete_slip: Delete a slip in Sanka.',
  '- download_slip_pdf: Download one slip as a PDF document.',
  '- list_bills: Review bills in Sanka.',
  '- get_bill: Load one bill in Sanka.',
  '- upload_bill_attachment: Upload a bill attachment and return a file_id.',
  '- create_bill: Create a bill in Sanka.',
  '- update_bill: Update a bill in Sanka.',
  '- delete_bill: Delete a bill in Sanka.',
  '- list_disbursements: Review disbursements in Sanka.',
  '- get_disbursement: Load one disbursement in Sanka.',
  '- create_disbursement: Create a disbursement in Sanka.',
  '- update_disbursement: Update a disbursement in Sanka.',
  '- delete_disbursement: Delete a disbursement in Sanka.',
  '- list_disbursement_allocations: Review bill and expense payable allocation rows for one disbursement in Sanka.',
  '- create_disbursement_allocation: Add one bill or expense payable allocation row to a disbursement.',
  '- update_disbursement_allocation: Update one bill or expense payable allocation row on a disbursement.',
  '- delete_disbursement_allocation: Archive/delete one bill or expense payable allocation row from a disbursement.',
  '- download_order_pdf: Download one order as a PDF document.',
  '- create_invoice: Create an invoice in Sanka.',
  '- update_invoice: Update an invoice in Sanka.',
  '- activate_invoice: Restore an archived invoice to active usage status in Sanka.',
  '- delete_invoice: Archive an invoice in Sanka. This is a soft delete, not a permanent delete.',
  '- permanent_delete_invoice: Permanently delete an already archived invoice in Sanka only when the user explicitly asks for permanent deletion and passes confirm=true.',
  '- list_subscriptions: Review subscriptions in Sanka.',
  '- get_subscription: Load one subscription in Sanka.',
  '- create_subscription: Create a subscription in Sanka.',
  '- update_subscription: Update a subscription in Sanka.',
  '- delete_subscription: Delete a subscription in Sanka.',
  '- list_payments: Review payments in Sanka.',
  '- get_payment: Load one payment in Sanka.',
  '- list_payment_allocations: Review invoice allocation rows for one payment in Sanka.',
  '- update_payment_allocations: Replace invoice allocation rows for one payment in Sanka.',
  '- create_payment: Create a payment in Sanka.',
  '- update_payment: Update a payment in Sanka.',
  '- delete_payment: Delete a payment in Sanka.',
  '- list_tickets: Review tickets in Sanka.',
  '- get_ticket: Load one ticket in Sanka.',
  '- create_ticket: Create a ticket in Sanka.',
  '- update_ticket: Update a ticket in Sanka.',
  '- delete_ticket: Delete a ticket in Sanka.',
  '- list_ticket_pipelines: List the ticket pipelines and stages defined in the workspace.',
  '- update_ticket_status: Update only the stage or status of a ticket in Sanka.',
  '- list_locations: Review locations in Sanka.',
  '- get_location: Load one location in Sanka.',
  '- create_location: Create a location in Sanka.',
  '- update_location: Update a location in Sanka.',
  '- delete_location: Delete a location in Sanka.',
  '- list_inventories: Review inventories in Sanka.',
  '- get_inventory: Load one inventory in Sanka.',
  '- create_inventory: Create an inventory record in Sanka.',
  '- update_inventory: Update an inventory record in Sanka.',
  '- delete_inventory: Delete an inventory record in Sanka.',
  '- list_inventory_transactions: Review inventory transactions in Sanka.',
  '- get_inventory_transaction: Load one inventory transaction in Sanka.',
  '- create_inventory_transaction: Create an inventory transaction in Sanka.',
  '- update_inventory_transaction: Update an inventory transaction in Sanka.',
  '- delete_inventory_transaction: Delete an inventory transaction in Sanka.',
  '- list_expenses: Review expense records in Sanka.',
  '- get_expense: Load one expense in Sanka.',
  '- upload_expense_attachment: Upload an expense attachment and return a file_id.',
  '- list_employees: Review the Sanka employee directory and resolve worker_id values for HR workflows.',
  '- list_absences: Review leave and absence records in Sanka.',
  '- get_absence: Load one leave or absence record.',
  '- create_absence: Create a leave or absence request.',
  '- update_absence: Update an existing leave or absence record.',
  '- delete_absence: Archive/delete a leave or absence record.',
  '- list_attendance_records: Review employee attendance/time tracking records. Do not confuse this with public calendar attendance bookings.',
  '- get_attendance_record: Load one employee attendance/time tracking record.',
  '- create_attendance_record: Create an employee attendance/time tracking record.',
  '- update_attendance_record: Update an employee attendance/time tracking record.',
  '- delete_attendance_record: Archive/delete an employee attendance/time tracking record.',
  '- list_payroll_profiles: Review employee payroll profiles.',
  '- upsert_payroll_profile: Create or update an employee payroll profile.',
  '- list_payroll_runs: Review payroll runs.',
  '- get_payroll_run: Load one payroll run and employee calculation results.',
  '- download_payroll_payslip_pdf: Download payroll payslips as a PDF document.',
  '- calculate_payroll_run: Calculate a payroll run for a period.',
  '- create_payroll_journal_entry: Create or reuse one monthly Sanka Journal Entry from a payroll run.',
  '- approve_payroll_run: Approve a calculated payroll run after explicit user confirmation.',
  '- list_incentives: Review calculated incentive and commission records in Sanka.',
  '- list_incentive_plans: Review incentive and commission rules in Sanka.',
  '- list_incentive_company_options: Search company records for incentive rule source or payee ids.',
  '- create_incentive_plan: Create an incentive or partner commission rule in Sanka.',
  '- calculate_incentives: Preview or store incentive calculations for a period.',
  '- approve_incentives: Approve draft incentives after explicit user confirmation.',
  '- generate_incentive_payment_notice: Draft a partner payment request notice from calculated incentives.',
  '- upload_import_file: Upload a CSV or similar import file and return a file_id.',
  '- import_records: Create a public import job from an uploaded file.',
  '- get_import_job: Load one import job by id.',
  '- list_import_jobs: List recent import jobs.',
  '- cancel_import_job: Cancel a running import job.',
  '- list_integration_channels: List connected export destinations and return channel ids.',
  '- export_records: Create a public export job for Sanka records.',
  '- get_export_job: Load one export job by id.',
  '- list_export_jobs: List recent export jobs.',
  '- cancel_export_job: Cancel a running export job.',
  '- create_expense: Create an expense in Sanka.',
  '- update_expense: Update an existing expense in Sanka.',
  '- delete_expense: Delete an expense in Sanka.',
  '- list_properties: Review object property definitions in Sanka or a connected integration.',
  '- get_property: Load one property definition in Sanka or a connected integration.',
  '- create_property: Create a custom property in Sanka or a connected integration.',
  '- update_property: Update a custom property in Sanka or a connected integration.',
  '- delete_property: Delete a custom property in Sanka or a connected integration.',
  '- list_approval_rules / get_approval_rule_options / upsert_approval_rule / delete_approval_rule: Review and manage approval rules for a Sanka object. Pass object such as invoices, companies, contacts, deals, payments, estimates, or orders.',
  '- list_lock_rules / get_lock_rule_options / upsert_lock_rule / delete_lock_rule: Review and manage record lock rules for a Sanka object. Pass object; invoice lock rules can target full records, financial fields, or selected fields.',
  '- list_delivery_rules / get_delivery_rule_options / upsert_delivery_rule / delete_delivery_rule: Review and manage delivery rules. Delivery rules currently support invoices and control send/schedule readiness and required fields.',
  '- list_object_schemas: Review Sanka custom object schemas or connected HubSpot/Salesforce object schemas.',
  '- mutate_object_schema: Create, update, or delete Sanka/HubSpot/Salesforce custom object schemas through routed arguments.',
  '- list_journal_entries: Review Sanka journal entries or statement rows from a saved journal PL/BS/CF view.',
  '- create_journal_statement_view: Create a Sanka journal Profit and Loss, Balance Sheet, or Cash Flow saved view from existing journal entries.',
  '- list_views: List saved views for any supported Sanka object.',
  '- get_view: Load one saved view by id.',
  '- get_view_columns: Load resolved columns for one saved view.',
  '- create_view: Create a saved view for any supported Sanka object.',
  '- update_view: Update a saved view for any supported Sanka object.',
  '- delete_view: Delete a saved view.',
  '- list_reports: Review Sanka reports and dashboards.',
  '- get_report: Load one Sanka report or dashboard.',
  '- create_report: Create a Sanka report or dashboard with optional panels.',
  '- update_report: Update a Sanka report or dashboard.',
  '- delete_report: Delete a Sanka report or dashboard.',
  '- get_calendar_bootstrap: Load the public calendar booking context for an event or attendance.',
  '- check_calendar_availability: Check available booking slots for a public calendar event.',
  '- create_calendar_attendance: Book a new public calendar attendance.',
  '- cancel_calendar_attendance: Cancel an existing public calendar attendance.',
  '- reschedule_calendar_attendance: Reschedule an existing public calendar attendance.',
  '- prospect_companies: Discover net-new companies from external sources using Sanka prospecting.',
  '- score_record: Score a company or deal in Sanka and explain the result.',
  '- generate_demo_workspace: Seed a workspace with curated demo CRM and billing data, or create demo records directly in HubSpot/Salesforce with target=integration after dry_run.',
  '- push_integration_sync: Emit outbound sync jobs for records to a connected integration channel.',
  '- browser_use: Run an allowlisted browser automation workflow through the governed Sanka browser-use layer, starting with demo.hubspot.company_avatar for HubSpot demo company avatars.',
  '',
  'Guardrails:',
  '- Treat private message, association, company, contact, deal, workflow run, item, order, purchase order, task, estimate, invoice, subscription, payment, slip, bill, disbursement, ticket, location, inventory, inventory transaction, custom object record, journal entry, saved view, report, expense, employee, absence, attendance record, payroll profile, payroll run, incentive, property, company pricing, calendar, prospecting, scoring, import, and export requests as live Sanka operations. Results and mutations must come from the dedicated MCP tools above.',
  '- If the user explicitly starts from the installed Sanka Plugin chip or names the Sanka Plugin, prefer the plugin-attached Sanka namespace in the current thread, usually `mcp__sanka_plugin__*`.',
  '- For private inbox messages, associations, companies, contacts, deals, workflow runs, items, orders, purchase orders, tasks, estimates, invoices, overdue invoices, subscriptions, payments, slips, bills, disbursements, tickets, locations, inventories, inventory transactions, custom object records, expenses, employees, absences, attendance records, payroll profiles, payroll runs, incentives, properties, company pricing, calendar workflows, prospecting, scoring, imports, or exports, call the matching protected tool directly without first calling auth_status or connect_sanka.',
  '- Native OAuth clients such as Codex and Claude should use the MCP OAuth challenge surfaced during connection or protected tool calls. Other clients may receive a Connect Sanka URL fallback from protected tool results.',
  '- Do not route plugin-scoped Sanka requests through stale global aliases such as `mcp__sanka_key__*`, `mcp__sanka__*`, or other duplicate global Sanka namespaces. Those can bypass the plugin attachment and surface raw auth errors.',
  '- The workspace_id parameter on data tools is not a workspace switcher. It expects the authenticated workspace internal UUID, not the short numeric workspace code shown in Sanka URLs. Usually omit workspace_id; use current_workspace, list_workspaces, and switch_workspace for workspace context or switching.',
  '- Do not render Sanka record numbers as Markdown issue references with a leading hash, for example hash followed by 7. Use safe labels such as "Invoice No. 7", "売上請求番号 7", or the UUID instead.',
  '- For Japanese user-facing replies, use Sanka object names precisely: Order is "受注" and Invoice is "売上請求". Do not translate them as "注文" or "請求書" unless quoting external source text.',
  '- For Japanese user-facing tables, show display labels for internal statuses. For example, status=draft should be shown as "下書き"; include the raw key only when explicitly useful, such as "下書き（draft）".',
  '- Do not say a Sanka tool or API call failed unless the tool result is isError or the structuredContent explicitly contains an error or HTTP status >= 400. If a later tool call succeeds, report the successful state.',
  '- If a protected tool is unavailable in the current client session, say the Sanka MCP server or plugin attachment is missing and ask the user to reconnect rather than guessing.',
  '- Never fabricate live Sanka data or substitute repo-local state, database access, or other out-of-band sources for dedicated Sanka tool results.',
  '',
  'Workflow:',
  '- Keep CRM queries narrow with search, pagination, workspace filters, or result limits when possible.',
  '- For integration-side company/contact/deal counts or lists, use aggregate_records, list_companies, list_contacts, or list_deals with scope=integration, provider=hubspot or provider=salesforce, and channel_id when multiple channels exist. HubSpot deals map to deals; Salesforce opportunities map to deals. For Sanka custom object rows, use query_records or aggregate_records with scope=sanka, object_type=custom_objects, and custom_object/custom_object_slug set to the custom object slug/internal key or id; display names are accepted as a fallback. Use create_custom_object_record, update_custom_object_record, or archive_custom_object_record for row mutations.',
  '- For record association work, use list_associations, create_association, and delete_association. There is no update_association tool; changing an association label should be handled as delete_association followed by create_association so the API can re-check label constraints.',
  '- For date- or stage-filtered integration deals, pass filters to list_deals or query_records instead of fetching all rows. The Sanka API accepts common aliases such as stage/dealstage/StageName and closed_at/closedate/CloseDate for HubSpot and Salesforce deal fields.',
  '- For duplicate discovery, use aggregate_records or query_records with mode=dedupe_candidates, match_fields such as ["name"] or ["email"], and a bounded scan_limit before any delete or dedupe mutation.',
  '- For Sanka orders and invoices, delete_order and delete_invoice are soft archive operations. Describe the result as archived / アーカイブ済み, not permanently deleted. Use permanent_delete_order or permanent_delete_invoice only when the user explicitly asks for permanent deletion, the record is already archived, and confirm=true is provided.',
  '- For integration-side HubSpot company create/update/delete/dedupe, use the existing create_company, update_company, or delete_company tools with target=integration or target=both. Salesforce integration records are read-only in these tools for now. Run dry_run=true first for Sanka or remote delete and dedupe, inspect sanka_action/warnings/sync_state, and set confirm=true only after the user explicitly approves the destructive action.',
  '- For integration-side HubSpot/Salesforce property schemas, use list_properties or get_property with scope=integration, provider=hubspot or provider=salesforce, and channel_id when multiple channels exist. HubSpot deals map to deals; Salesforce opportunities map to deals.',
  '- For remote property create/update/delete, use create_property, update_property, or delete_property with target=integration or target=both. Run dry_run=true first for remote property writes, and set confirm=true only after the user explicitly approves a delete. Salesforce property writes are limited to custom fields ending in __c.',
  '- For Sanka company cycles, billing_cycle and payment_cycle are standard company fields, not a custom-property creation flow. Set them directly with create_company/update_company top-level inputs: billing_cycle="end" for 月末締め or "1" through "31" for a closing day; payment_cycle="nmonth_end" for 翌月末払い, "cmonth_end" for 当月末払い, or net terms such as "net_30". If the user only says "月末" for payment cycle, ask whether they mean current-month end or next-month end.',
  '- For custom object schema management, use list_object_schemas and mutate_object_schema with scope/target=sanka|integration|both. HubSpot schema writes use HubSpot object schema APIs; Salesforce schema writes use Metadata API. Always run dry_run=true first, and require confirm=true for deletes.',
  '- For rule settings, use approval-rules, lock-rules, and delivery-rules tools with object rather than object-specific endpoints. Use approval rules when an action must wait for approval; use lock rules when a matching record should not be edited; use delivery rules when invoice send/schedule readiness or required fields should change. Delivery rules are invoice-only for now.',
  '- For journal-backed P&L, balance sheet, or cash-flow requests, use create_journal_statement_view first to create the saved view, then use list_journal_entries with the returned view_id when you need to read the generated statement rows.',
  '- For normal saved view requests, use create_view/list_views/get_view/get_view_columns/update_view/delete_view instead of object-specific workarounds. Pass object names such as orders, invoices, companies, contacts, deals, tickets, tasks, custom_object, dashboards, or panels.',
  '- For report/dashboard creation, use create_report. Use list_reports/get_report to inspect reports before updates or deletes.',
  '- Use list_private_messages for the private account-level inbox. Do not confuse it with Sanka shared group inbox workflows.',
  '- Start reply flows with get_private_message_thread when you need the current thread history or reply target.',
  '- Use sync_private_messages before replying when the user asks for the latest state from Gmail or another connected private inbox channel.',
  '- Use get_company_price_table when the user asks for company-specific item pricing, and use search to narrow to one item when possible.',
  '- For create_subscription, use exactly one customer identifier: contact_id, company_id, or customer_id. Company-only customers are valid. When converting invoice or order lines, fetch the source record first and pass line_items/items with item_id when present, or name plus amount/quantity and price/unit_price when no linked item_id exists.',
  '- For leave requests such as vacation, PTO, sick leave, or absences, use create_absence/list_absences/get_absence/update_absence/delete_absence rather than tasks or calendar bookings.',
  '- For employee work attendance and time tracking, use list_attendance_records/get_attendance_record/create_attendance_record/update_attendance_record/delete_attendance_record; reserve create_calendar_attendance for public event booking only.',
  '- For payroll setup and calculations, use list_payroll_profiles/upsert_payroll_profile and list_payroll_runs/get_payroll_run/calculate_payroll_run. Use create_payroll_journal_entry when the user wants a monthly payroll run posted to Sanka Journal Entries. Use download_payroll_payslip_pdf when the user explicitly asks for payroll payslip PDFs. Use approve_payroll_run only after explicit user confirmation.',
  '- Keep item, subscription, payment, location, inventory, and inventory transaction queries narrow with workspace filters and local limits because those public endpoints return arrays.',
  '- Prefer list_deal_pipelines before describing deal stages so stage labels and ordering match the workspace configuration.',
  '- Use get_estimate for normal estimate lookups. Only use download_estimate_pdf when the user explicitly asks for a PDF, file, attachment, download, or rendered PDF inspection.',
  '- For Sanka object URL requests, call the matching get_* tool when needed and return app_url from the object payload or workflow-created record result. Do not ask the user to copy the URL from the Sanka UI when app_url is present.',
  '- PDF download tools return download_complete=true plus content_base64 for small files. For large files, download_complete=false and content_base64_available=false; this is not a completed user download. If download_url is present, fetch that URL directly and attach or save the PDF before telling the user the download is complete. Only call read_binary_download_chunk when download_url is absent or the direct download fails; then concatenate content_base64 chunks in order, decode the combined base64 string, and attach or save the decoded PDF. Do not call resources/read for resource://tool-response.',
  '- For invoice email sending, use send_invoice_email rather than changing invoice status. For scheduled sends, pass action="schedule" and scheduled_at as an ISO datetime in the user/workspace timezone.',
  '- If a PDF download returns 404 after the record was visible earlier, verify current_workspace/list_workspaces and use switch_workspace with the internal workspace UUID before retrying. Record numbers and UUID lookups are workspace-context dependent; do not retry numeric IDs in a different workspace as if they were globally safe.',
  '- For subscription record edits such as start date, end date, status, or linked contract changes, use update_subscription directly. Pass start_date/end_date as ISO dates and contract_id or contract_ids for Sanka Contract associations; pass an empty contract_ids array only when the user explicitly wants to clear linked contracts.',
  '- For lead-to-cash workflow requests like creating or previewing an estimate from a deal, use preview_workflow directly when the user gives a HubSpot Deal URL; pass workflow_type=deal_to_estimate, source_record.source_system=hubspot, object_type=deal, and source_record.url. Do not ask the user to explain Sanka sync behavior. The API will use a synced Sanka deal if available, otherwise use authorized HubSpot access for read-only preview and supported execution. Use resolve_record only when the source phrase is ambiguous and no URL/id is present. Use start_workflow to create the estimate draft and approval request only after explicit user confirmation, and get_workflow_run for status.',
  '- For CRM-origin invoice requests such as "create an invoice from this HubSpot Deal" or Salesforce Opportunity billing, do not call deal_to_invoice or create_invoice directly from the CRM record. Preview the source with workflow_type=deal_to_order, tell the user that Sanka will first create or reuse a Sanka Order so billing can be generated correctly, ask for explicit confirmation, then start_workflow with workflow_type=deal_to_order. Create invoices only from the resulting Sanka Order with workflow_type=order_to_invoice. freee sync is a separate invoice_export workflow step; after creating invoices from Orders, preview invoice_export with sync_scope=created_in_workflow_run or selected_invoice_ids, then start invoice_export only after explicit user approval.',
  '- For Sanka Estimate invoice requests such as "create an invoice from this estimate", use workflow_type=estimate_to_invoice with source_record.source_system=sanka, object_type=estimate, and the Sanka Estimate id. Explain that Sanka will create or reuse a Sanka Order from the Estimate before creating the Invoice.',
  '- For CRM-origin subscription requests such as "create subscriptions from HubSpot Deals" or "bulk-create subscriptions from deals with a subscription flag", use workflow_type=deal_to_subscription. For HubSpot batch lists, pass source_record.source_system=hubspot, object_type=deal, portal_id or channel_id, and options such as subscription_flag_property plus subscription_flag_value or subscription_flag_values. Preview first, explain that Sanka will create or reuse Orders before creating Subscriptions, then start only after explicit confirmation.',
  '- For Sanka Subscription invoice requests such as "create invoices from these subscriptions", use workflow_type=subscription_to_invoice with source_record.source_system=sanka, object_type=subscription, and one record_id or options.subscription_ids for a batch. Pass start_date and due_date when the user gives the target billing period or payment terms. Preview first when the scope is broad or ambiguous.',
  '- For CRM-origin procurement requests such as "if this HubSpot Deal lacks inventory, create a purchase order", do not create a purchase order directly from the CRM deal/opportunity. First route the CRM record through deal_to_order, explain that Sanka will create or reuse the Sanka Order first, ask for explicit confirmation, then use workflow_type=order_to_purchase_order with the resulting Sanka Order. order_to_purchase_order previews shortage lines and creates purchase orders only for detected inventory shortages.',
  '- For Disbursement to Expense or Bill payable links, use list_disbursement_allocations/create_disbursement_allocation/update_disbursement_allocation/delete_disbursement_allocation. Do not use generic association tools for Expense <> Disbursement because that relationship is DisbursementPayableAllocation-backed.',
  '- For HubSpot order or fulfillment handoff requests such as "move this HubSpot deal to order processing", "create an order draft from this HubSpot Deal", "preview fulfillment handoff", or "check inventory and delivery timing", call preview_workflow with workflow_type=deal_to_order_handoff, source_record.source_system=hubspot, object_type=deal, and the HubSpot Deal id or URL. Summarize customer/contact resolution, line items, inventory availability, shortages, lead-time and delivery timing, duplicate order or handoff warnings, blockers, and required_confirmation. Missing inventory or lead-time data is a limitation to report, not a reason to invent data. Call start_workflow only after explicit confirmation; pass a stable idempotency_key and allow_duplicate_order only when the user explicitly approved another order. HubSpot writeback happens only after successful Sanka order or handoff creation.',
  '- For freee invoice draft sync requests, use preview_workflow with workflow_type=invoice_export, source_record.source_system=sanka, source_record.object_type=invoice, options.target_system=freee, and an explicit sync_scope. Prefer created_in_workflow_run after an order_to_invoice run or selected_invoice_ids for user-selected invoices. If the user only says to sync Sanka invoices to freee invoice drafts without a scope, do not call start_workflow; preview returns needs_confirmation with options, or ask the user to choose. all_eligible_unsynced requires confirm_all=true and explicit user confirmation. Re-sync or multiple freee drafts require allow_resync or allow_multiple_freee_drafts plus user intent.',
  '- For HubSpot revenue control questions such as "summarize this month\'s HubSpot revenue", "show unbilled deals", "show approval waits", "show unpaid invoices", or "what revenue is blocked?", call preview_workflow with workflow_type=revenue_control_summary, source_record.source_system=hubspot, object_type=deal, and options for start_date/end_date or date_range. Summarize won, quote_drafted, approval_pending, unbilled, invoiced, unpaid, blocked, totals by currency/owner/customer/aging, top_blockers, and next_actions. This is read-only; do not call start_workflow or mutate HubSpot, Sanka, freee, or Stripe records. For sales incentive or commission questions such as "calculate April commissions", "calculate this month sales incentives by rep", "show draft commissions", or "flag unpaid or low-margin deals", call preview_workflow with workflow_type=sales_incentive_commission, source_record.source_system=hubspot, object_type=deal, and options for period/date range, channel_id, CRM owner/rep/customer filters, include_records/include_excluded, include_payment_status, include_margin, include_refunds, and compensation_rule_id or plan_id when needed. Summarize total reps, included/excluded/flagged deals, eligible and commission totals by currency, rule version/snapshot, rep summaries, deal explanations, unpaid/refund/low-margin/unmapped exceptions, warnings, and suggested next actions. This is draft/read-only; do not call start_workflow or mutate HubSpot, Salesforce, Sanka invoices/orders/payments, freee, Stripe, platform mappings, compensation rules, payouts, or approvals.',
  '- For Salesforce quote-readiness questions such as "Can this Salesforce Opportunity be quoted?", call preview_workflow with workflow_type=quote_readiness, source_record.source_system=salesforce, object_type=opportunity, and the Salesforce Opportunity id or URL. The tool routes this read-only CPQ business preview through Sanka quote-readiness routes where Salesforce is the source platform. Summarize ready, target_record, financials, line item checks, approval, hard_blockers, warnings, suggested_fixes, source_records, sanka_records, and orchestration_plan. Do not call Salesforce-specific all-in-one create tools; compose generic Sanka search/create/estimate/workflow tools only when a later create flow is explicitly supported and requested.',
  '- For orders, provide line items inside the nested `order` payload and prefer external references for linked companies or items when available.',
  '- For purchase orders, slips, bills, and disbursements, prefer linked company or contact ids/external references when the user already has those records in Sanka.',
  '- Prefer get_item before applying company price overrides when you need to confirm the default item price or item identity.',
  '- Use list_tasks or get_task before updating a task when the user wants to append to the current description, because task updates replace the field you send.',
  '- Prefer list_ticket_pipelines before moving tickets across stages so stage keys and labels match the workspace configuration.',
  '- Prefer list_properties or get_property before mutating object records or property definitions when you need to confirm the current schema.',
  '- Start booking, rescheduling, or cancellation flows with get_calendar_bootstrap when you need the event context or existing attendance details.',
  '- Use check_calendar_availability before create_calendar_attendance or reschedule_calendar_attendance when the user needs the next available slot.',
  '- Prefer update_ticket_status over update_ticket when only the stage or status is changing.',
  '- Use prospect_companies when the user wants external company discovery or target-account research rather than only searching existing CRM records.',
  '- Use score_record when the user wants qualification, prioritization, or a transparent explanation of why a company or deal is strong or weak.',
  '- Use generate_demo_workspace when the user wants a fast sandbox or reproducible demo workspace with realistic lead-to-cash data. For direct HubSpot/Salesforce demo creation, call it with target=integration, provider, dry_run=true first, then confirm=true only after explicit approval. For provider custom object demo records, pass custom_objects with external_object_type and records or count/name_property; the custom object schema must already exist.',
  '- Use push_integration_sync after a user edits or seeds records and explicitly wants those changes pushed to a connected downstream system.',
  '- Use browser_use only for registered browser workflows when a third-party API cannot perform the requested operation. For HubSpot demo company avatars, use workflow="demo.hubspot.company_avatar", driver="agent_browser", dry_run=true first, then run with dry_run=false and confirm=true only after the dry run is reviewed. Do not use browser_use for open-ended browsing or arbitrary web instructions.',
  '- HubSpot company avatar note: hs_logo_url can be updated by API but does not control the visible round record/list avatar. The visible avatar is backed by HubSpot-managed state such as hs_avatar_filemanager_key, which is read-only through public CRM property updates, so demo avatar updates must go through the registered browser workflow or be left as default HubSpot icons.',
  '- When a create tool returns a governance advisory such as missing_recommended_partner, report that the record was created and ask for explicit permission before creating or linking a company/contact.',
  '- Use upload_expense_attachment before create_expense or update_expense when the user wants a receipt or invoice attached.',
  '- upload_expense_attachment expects filename plus content_base64. Do not assume the hosted MCP server can read a client-local file path.',
  '- Use upload_bill_attachment before create_bill or update_bill when the user wants a bill file attached.',
  '- upload_bill_attachment expects filename plus content_base64. Do not assume the hosted MCP server can read a client-local file path.',
  '- Use list_employees to resolve the full employee directory. Do not infer employees from absences, attendance records, or payroll profiles because those only show employees with related HR records.',
  '- Use upload_order_attachment, upload_purchase_order_attachment, upload_estimate_attachment, or upload_invoice_attachment before the matching create/update tool when the user wants a file attached.',
  '- Document attachment upload tools expect filename plus content_base64. Do not assume the hosted MCP server can read a client-local file path.',
  '- For partner commissions, resolve the partner company id with list_incentive_company_options or list_companies, create an invoice_paid company-payee rule with create_incentive_plan, run calculate_incentives with dry_run=true first, then set dry_run=false only when the user wants draft incentives stored. Use approve_incentives only after explicit approval.',
  '- Use generate_incentive_payment_notice when the user asks for a partner payment request or invoice-request notice from calculated incentives.',
  '- Use upload_import_file before import_records when the user starts from a local CSV or spreadsheet export.',
  '- Use list_integration_channels before export_records when the user does not already know the destination channel_id.',
  '- Use connect_sanka when the user explicitly asks to connect or reconnect Sanka without retrying a protected action first.',
  '- If a protected tool reports missing authentication and structuredContent.required_user_facing_reply is present, include that field verbatim in the next visible response before stopping; it contains the exact full Connect Sanka URL. Do not omit the URL, hide it behind a short label like "Connect Sanka", abbreviate the token, replace it with "...", or only tell the user to reconnect. If the field is missing, call auth_status so the tool result can surface reconnect metadata. Do not fabricate login URLs. Then tell the user to retry after reconnecting.',
  '- Individual HTTP requests to the API have a 30-second timeout. If a request times out, try a smaller query or add filters.',
].join('\n');

interface InstructionsCacheEntry {
  fetchedInstructions: string;
  fetchedAt: number;
}

const instructionsCache = new Map<string, InstructionsCacheEntry>();

export async function getInstructions({
  customInstructionsPath,
  toolProfile = 'full',
}: {
  customInstructionsPath?: string | undefined;
  toolProfile?: ToolProfile | undefined;
}): Promise<string> {
  const now = Date.now();
  const cacheKey = `${customInstructionsPath ?? '__default__'}:${toolProfile}`;
  const cached = instructionsCache.get(cacheKey);

  if (cached && now - cached.fetchedAt <= INSTRUCTIONS_CACHE_TTL_MS) {
    return cached.fetchedInstructions;
  }

  // Evict stale entries so the cache doesn't grow unboundedly.
  for (const [key, entry] of instructionsCache) {
    if (now - entry.fetchedAt > INSTRUCTIONS_CACHE_TTL_MS) {
      instructionsCache.delete(key);
    }
  }

  let fetchedInstructions: string;

  if (customInstructionsPath) {
    fetchedInstructions = await fetchLatestInstructionsFromFile(customInstructionsPath);
  } else {
    fetchedInstructions = toolProfile === 'hosted' ? DEFAULT_HOSTED_INSTRUCTIONS : DEFAULT_FULL_INSTRUCTIONS;
  }

  instructionsCache.set(cacheKey, { fetchedInstructions, fetchedAt: now });
  return fetchedInstructions;
}

async function fetchLatestInstructionsFromFile(path: string): Promise<string> {
  try {
    return await fs.readFile(path, 'utf-8');
  } catch (error) {
    getLogger().error({ error, path }, 'Error fetching instructions from file');
    throw error;
  }
}
