import { configureLogger } from '../../packages/mcp-server/src/logger';
import { recordMcpToolCall, selectTools } from '../../packages/mcp-server/src/server';
import { getInstructions } from '../../packages/mcp-server/src/instructions';
import { applyRequiredScopesToSecuritySchemes } from '../../packages/mcp-server/src/tool-scope-requirements';

describe('profile-aware tool selection', () => {
  beforeAll(() => {
    configureLogger({ level: 'error', pretty: false });
  });

  it('records MCP tool calls through the V2 audit route', async () => {
    const post = jest.fn().mockResolvedValue({});
    const logger = { warn: jest.fn() };

    await recordMcpToolCall({
      client: { post } as never,
      logger,
      mcpTool: {
        tool: { name: 'list_deals', title: 'List deals' },
        metadata: { resource: 'deals', operation: 'list' },
      } as never,
      reqContext: {
        mcpSessionId: 'mcp-session-1',
        auth: { authMode: 'oauth_bearer' },
        mcpClientInfo: { name: 'Claude', version: '1.0.0' },
      } as never,
      result: { content: [], isError: false },
      startedAt: Date.now() - 12,
    });

    expect(post).toHaveBeenCalledWith('/api/v2/mcp/tool-call-log', {
      body: expect.objectContaining({
        tool_name: 'list_deals',
        tool_title: 'List deals',
        resource: 'deals',
        operation: 'list',
        success: true,
        client_name: 'Claude',
        client_version: '1.0.0',
      }),
      headers: { 'X-Sanka-MCP-Session-ID': 'mcp-session-1' },
    });
    expect(logger.warn).not.toHaveBeenCalled();
  });

  it('exposes the unified toolset from the full profile', () => {
    const toolNames = selectTools(undefined, 'full').map((tool) => tool.tool.name);

    expect(toolNames).toContain('execute');
    expect(toolNames).toContain('search_docs');
    expect(toolNames).toContain('connect_sanka');
    expect(toolNames).toContain('auth_status');
    expect(toolNames).toContain('read_binary_download_chunk');
    expect(toolNames).toContain('list_private_messages');
    expect(toolNames).toContain('sync_private_messages');
    expect(toolNames).toContain('get_private_message_thread');
    expect(toolNames).toContain('reply_private_message_thread');
    expect(toolNames).toContain('archive_private_message_thread');
    expect(toolNames).toContain('list_workspace_messages');
    expect(toolNames).toContain('sync_workspace_messages');
    expect(toolNames).toContain('get_workspace_message_thread');
    expect(toolNames).toContain('list_associations');
    expect(toolNames).toContain('create_association');
    expect(toolNames).toContain('delete_association');
    expect(toolNames).toContain('list_companies');
    expect(toolNames).toContain('get_company');
    expect(toolNames).toContain('create_company');
    expect(toolNames).toContain('update_company');
    expect(toolNames).toContain('delete_company');
    expect(toolNames).toContain('get_company_price_table');
    expect(toolNames).toContain('update_company_price_table_company');
    expect(toolNames).toContain('update_company_price_table_item');
    expect(toolNames).toContain('apply_company_price_table_items');
    expect(toolNames).toContain('list_contacts');
    expect(toolNames).toContain('get_contact');
    expect(toolNames).toContain('create_contact');
    expect(toolNames).toContain('update_contact');
    expect(toolNames).toContain('delete_contact');
    expect(toolNames).toContain('list_deals');
    expect(toolNames).toContain('get_deal');
    expect(toolNames).toContain('create_deal');
    expect(toolNames).toContain('update_deal');
    expect(toolNames).toContain('delete_deal');
    expect(toolNames).toContain('list_deal_pipelines');
    expect(toolNames).toContain('capture_pipeline_snapshot');
    expect(toolNames).toContain('compare_pipeline_snapshots');
    expect(toolNames).toContain('sync_pipeline_snapshot_hubspot_properties');
    expect(toolNames).toContain('list_items');
    expect(toolNames).toContain('get_item');
    expect(toolNames).toContain('create_item');
    expect(toolNames).toContain('update_item');
    expect(toolNames).toContain('delete_item');
    expect(toolNames).toContain('list_orders');
    expect(toolNames).toContain('get_order');
    expect(toolNames).toContain('create_order');
    expect(toolNames).toContain('update_order');
    expect(toolNames).toContain('activate_order');
    expect(toolNames).toContain('delete_order');
    expect(toolNames).toContain('permanent_delete_order');
    expect(toolNames).toContain('list_purchase_orders');
    expect(toolNames).toContain('get_purchase_order');
    expect(toolNames).toContain('download_purchase_order_pdf');
    expect(toolNames).toContain('create_purchase_order');
    expect(toolNames).toContain('update_purchase_order');
    expect(toolNames).toContain('delete_purchase_order');
    expect(toolNames).toContain('list_estimates');
    expect(toolNames).toContain('get_estimate');
    expect(toolNames).toContain('create_estimate');
    expect(toolNames).toContain('update_estimate');
    expect(toolNames).toContain('delete_estimate');
    expect(toolNames).toContain('list_invoices');
    expect(toolNames).toContain('list_overdue_invoices');
    expect(toolNames).toContain('get_invoice');
    expect(toolNames).toContain('send_invoice_email');
    expect(toolNames).toContain('create_invoice');
    expect(toolNames).toContain('update_invoice');
    expect(toolNames).toContain('activate_invoice');
    expect(toolNames).toContain('delete_invoice');
    expect(toolNames).toContain('permanent_delete_invoice');
    expect(toolNames).toContain('list_subscriptions');
    expect(toolNames).toContain('get_subscription');
    expect(toolNames).toContain('create_subscription');
    expect(toolNames).toContain('update_subscription');
    expect(toolNames).toContain('delete_subscription');
    expect(toolNames).toContain('list_payments');
    expect(toolNames).toContain('get_payment');
    expect(toolNames).toContain('list_payment_allocations');
    expect(toolNames).toContain('update_payment_allocations');
    expect(toolNames).toContain('create_payment');
    expect(toolNames).toContain('update_payment');
    expect(toolNames).toContain('delete_payment');
    expect(toolNames).toContain('list_slips');
    expect(toolNames).toContain('get_slip');
    expect(toolNames).toContain('create_slip');
    expect(toolNames).toContain('update_slip');
    expect(toolNames).toContain('delete_slip');
    expect(toolNames).toContain('list_bills');
    expect(toolNames).toContain('get_bill');
    expect(toolNames).toContain('upload_bill_attachment');
    expect(toolNames).toContain('create_bill');
    expect(toolNames).toContain('update_bill');
    expect(toolNames).toContain('delete_bill');
    expect(toolNames).toContain('list_disbursements');
    expect(toolNames).toContain('get_disbursement');
    expect(toolNames).toContain('create_disbursement');
    expect(toolNames).toContain('update_disbursement');
    expect(toolNames).toContain('delete_disbursement');
    expect(toolNames).toContain('list_disbursement_allocations');
    expect(toolNames).toContain('create_disbursement_allocation');
    expect(toolNames).toContain('update_disbursement_allocation');
    expect(toolNames).toContain('delete_disbursement_allocation');
    expect(toolNames).toContain('list_tickets');
    expect(toolNames).toContain('get_ticket');
    expect(toolNames).toContain('create_ticket');
    expect(toolNames).toContain('update_ticket');
    expect(toolNames).toContain('delete_ticket');
    expect(toolNames).toContain('list_ticket_pipelines');
    expect(toolNames).toContain('update_ticket_status');
    expect(toolNames).toContain('list_locations');
    expect(toolNames).toContain('get_location');
    expect(toolNames).toContain('create_location');
    expect(toolNames).toContain('update_location');
    expect(toolNames).toContain('delete_location');
    expect(toolNames).toContain('list_inventories');
    expect(toolNames).toContain('get_inventory');
    expect(toolNames).toContain('create_inventory');
    expect(toolNames).toContain('update_inventory');
    expect(toolNames).toContain('delete_inventory');
    expect(toolNames).toContain('list_inventory_transactions');
    expect(toolNames).toContain('get_inventory_transaction');
    expect(toolNames).toContain('create_inventory_transaction');
    expect(toolNames).toContain('update_inventory_transaction');
    expect(toolNames).toContain('delete_inventory_transaction');
    expect(toolNames).toContain('list_expenses');
    expect(toolNames).toContain('get_expense');
    expect(toolNames).toContain('upload_expense_attachment');
    expect(toolNames).toContain('start_expense_attachment_upload');
    expect(toolNames).toContain('append_expense_attachment_upload_chunk');
    expect(toolNames).toContain('finish_expense_attachment_upload');
    expect(toolNames).toContain('upload_order_attachment');
    expect(toolNames).toContain('upload_purchase_order_attachment');
    expect(toolNames).toContain('upload_estimate_attachment');
    expect(toolNames).toContain('upload_invoice_attachment');
    expect(toolNames).toContain('upload_import_file');
    expect(toolNames).toContain('import_records');
    expect(toolNames).toContain('get_import_job');
    expect(toolNames).toContain('list_import_jobs');
    expect(toolNames).toContain('cancel_import_job');
    expect(toolNames).toContain('list_integration_channels');
    expect(toolNames).toContain('export_records');
    expect(toolNames).toContain('get_export_job');
    expect(toolNames).toContain('list_export_jobs');
    expect(toolNames).toContain('cancel_export_job');
    expect(toolNames).toContain('create_expense');
    expect(toolNames).toContain('update_expense');
    expect(toolNames).toContain('delete_expense');
    expect(toolNames).toContain('list_employees');
    expect(toolNames).toContain('list_absences');
    expect(toolNames).toContain('get_absence');
    expect(toolNames).toContain('create_absence');
    expect(toolNames).toContain('update_absence');
    expect(toolNames).toContain('delete_absence');
    expect(toolNames).toContain('list_attendance_records');
    expect(toolNames).toContain('get_attendance_record');
    expect(toolNames).toContain('create_attendance_record');
    expect(toolNames).toContain('update_attendance_record');
    expect(toolNames).toContain('delete_attendance_record');
    expect(toolNames).toContain('list_payroll_profiles');
    expect(toolNames).toContain('upsert_payroll_profile');
    expect(toolNames).toContain('list_payroll_runs');
    expect(toolNames).toContain('get_payroll_run');
    expect(toolNames).toContain('download_payroll_payslip_pdf');
    expect(toolNames).toContain('calculate_payroll_run');
    expect(toolNames).toContain('create_payroll_journal_entry');
    expect(toolNames).toContain('approve_payroll_run');
    expect(toolNames).toContain('list_incentives');
    expect(toolNames).toContain('list_incentive_plans');
    expect(toolNames).toContain('list_incentive_company_options');
    expect(toolNames).toContain('create_incentive_plan');
    expect(toolNames).toContain('calculate_incentives');
    expect(toolNames).toContain('approve_incentives');
    expect(toolNames).toContain('generate_incentive_payment_notice');
    expect(toolNames).toContain('list_properties');
    expect(toolNames).toContain('get_property');
    expect(toolNames).toContain('create_property');
    expect(toolNames).toContain('update_property');
    expect(toolNames).toContain('delete_property');
    expect(toolNames).toContain('create_approval_request');
    expect(toolNames).toContain('list_record_approvals');
    expect(toolNames).toContain('approve_record_approval');
    expect(toolNames).toContain('reject_record_approval');
    expect(toolNames).toContain('list_approval_rules');
    expect(toolNames).toContain('get_approval_rule_options');
    expect(toolNames).toContain('upsert_approval_rule');
    expect(toolNames).toContain('delete_approval_rule');
    expect(toolNames).toContain('list_lock_rules');
    expect(toolNames).toContain('get_lock_rule_options');
    expect(toolNames).toContain('upsert_lock_rule');
    expect(toolNames).toContain('delete_lock_rule');
    expect(toolNames).toContain('list_delivery_rules');
    expect(toolNames).toContain('get_delivery_rule_options');
    expect(toolNames).toContain('upsert_delivery_rule');
    expect(toolNames).toContain('delete_delivery_rule');
    expect(toolNames).toContain('get_calendar_bootstrap');
    expect(toolNames).toContain('check_calendar_availability');
    expect(toolNames).toContain('create_calendar_attendance');
    expect(toolNames).toContain('cancel_calendar_attendance');
    expect(toolNames).toContain('reschedule_calendar_attendance');
    expect(toolNames).toContain('prospect_companies');
    expect(toolNames).toContain('score_record');
    expect(toolNames).toContain('generate_demo_workspace');
    expect(toolNames).toContain('push_integration_sync');
  });

  it('does not register duplicate tool names', () => {
    for (const profile of ['full', 'hosted'] as const) {
      const toolNames = selectTools(undefined, profile).map((tool) => tool.tool.name);
      expect(toolNames).toHaveLength(new Set(toolNames).size);
    }
  });

  it('keeps cleanup tools available for workflow-created records', () => {
    const workflowCleanupTools = [
      'delete_estimate',
      'delete_order',
      'delete_invoice',
      'delete_subscription',
      'delete_purchase_order',
      'delete_task',
    ];

    for (const profile of ['full', 'hosted'] as const) {
      const selectedTools = selectTools(undefined, profile);
      const toolsByName = new Map(selectedTools.map((selected) => [selected.tool.name, selected.tool]));

      for (const toolName of workflowCleanupTools) {
        const tool = toolsByName.get(toolName);
        expect(tool).toBeDefined();
        expect(tool?.annotations?.destructiveHint).toBe(true);
      }
    }
  });

  it('hides generic docs/code tools from the hosted profile', () => {
    const toolNames = selectTools(undefined, 'hosted').map((tool) => tool.tool.name);

    expect(toolNames).not.toContain('execute');
    expect(toolNames).not.toContain('search_docs');
    expect(toolNames).toContain('connect_sanka');
    expect(toolNames).toContain('auth_status');
    expect(toolNames).toContain('list_private_messages');
    expect(toolNames).toContain('sync_private_messages');
    expect(toolNames).toContain('get_private_message_thread');
    expect(toolNames).toContain('reply_private_message_thread');
    expect(toolNames).toContain('archive_private_message_thread');
    expect(toolNames).toContain('list_workspace_messages');
    expect(toolNames).toContain('sync_workspace_messages');
    expect(toolNames).toContain('get_workspace_message_thread');
    expect(toolNames).toContain('list_associations');
    expect(toolNames).toContain('create_association');
    expect(toolNames).toContain('delete_association');
    expect(toolNames).toContain('list_companies');
    expect(toolNames).toContain('get_company');
    expect(toolNames).toContain('create_company');
    expect(toolNames).toContain('update_company');
    expect(toolNames).toContain('delete_company');
    expect(toolNames).toContain('get_company_price_table');
    expect(toolNames).toContain('update_company_price_table_company');
    expect(toolNames).toContain('update_company_price_table_item');
    expect(toolNames).toContain('apply_company_price_table_items');
    expect(toolNames).toContain('list_contacts');
    expect(toolNames).toContain('get_contact');
    expect(toolNames).toContain('create_contact');
    expect(toolNames).toContain('update_contact');
    expect(toolNames).toContain('delete_contact');
    expect(toolNames).toContain('list_deals');
    expect(toolNames).toContain('get_deal');
    expect(toolNames).toContain('create_deal');
    expect(toolNames).toContain('update_deal');
    expect(toolNames).toContain('delete_deal');
    expect(toolNames).toContain('list_deal_pipelines');
    expect(toolNames).toContain('capture_pipeline_snapshot');
    expect(toolNames).toContain('compare_pipeline_snapshots');
    expect(toolNames).toContain('sync_pipeline_snapshot_hubspot_properties');
    expect(toolNames).toContain('list_items');
    expect(toolNames).toContain('get_item');
    expect(toolNames).toContain('create_item');
    expect(toolNames).toContain('update_item');
    expect(toolNames).toContain('delete_item');
    expect(toolNames).toContain('list_orders');
    expect(toolNames).toContain('get_order');
    expect(toolNames).toContain('create_order');
    expect(toolNames).toContain('update_order');
    expect(toolNames).toContain('activate_order');
    expect(toolNames).toContain('delete_order');
    expect(toolNames).toContain('permanent_delete_order');
    expect(toolNames).toContain('list_purchase_orders');
    expect(toolNames).toContain('get_purchase_order');
    expect(toolNames).toContain('download_purchase_order_pdf');
    expect(toolNames).toContain('create_purchase_order');
    expect(toolNames).toContain('update_purchase_order');
    expect(toolNames).toContain('delete_purchase_order');
    expect(toolNames).toContain('list_estimates');
    expect(toolNames).toContain('get_estimate');
    expect(toolNames).toContain('create_estimate');
    expect(toolNames).toContain('update_estimate');
    expect(toolNames).toContain('delete_estimate');
    expect(toolNames).toContain('list_invoices');
    expect(toolNames).toContain('list_overdue_invoices');
    expect(toolNames).toContain('get_invoice');
    expect(toolNames).toContain('send_invoice_email');
    expect(toolNames).toContain('create_invoice');
    expect(toolNames).toContain('update_invoice');
    expect(toolNames).toContain('activate_invoice');
    expect(toolNames).toContain('delete_invoice');
    expect(toolNames).toContain('permanent_delete_invoice');
    expect(toolNames).toContain('list_subscriptions');
    expect(toolNames).toContain('get_subscription');
    expect(toolNames).toContain('create_subscription');
    expect(toolNames).toContain('update_subscription');
    expect(toolNames).toContain('delete_subscription');
    expect(toolNames).toContain('list_payments');
    expect(toolNames).toContain('get_payment');
    expect(toolNames).toContain('list_payment_allocations');
    expect(toolNames).toContain('update_payment_allocations');
    expect(toolNames).toContain('create_payment');
    expect(toolNames).toContain('update_payment');
    expect(toolNames).toContain('delete_payment');
    expect(toolNames).toContain('list_slips');
    expect(toolNames).toContain('get_slip');
    expect(toolNames).toContain('create_slip');
    expect(toolNames).toContain('update_slip');
    expect(toolNames).toContain('delete_slip');
    expect(toolNames).toContain('list_bills');
    expect(toolNames).toContain('get_bill');
    expect(toolNames).toContain('upload_bill_attachment');
    expect(toolNames).toContain('create_bill');
    expect(toolNames).toContain('update_bill');
    expect(toolNames).toContain('delete_bill');
    expect(toolNames).toContain('list_disbursements');
    expect(toolNames).toContain('get_disbursement');
    expect(toolNames).toContain('create_disbursement');
    expect(toolNames).toContain('update_disbursement');
    expect(toolNames).toContain('delete_disbursement');
    expect(toolNames).toContain('list_disbursement_allocations');
    expect(toolNames).toContain('create_disbursement_allocation');
    expect(toolNames).toContain('update_disbursement_allocation');
    expect(toolNames).toContain('delete_disbursement_allocation');
    expect(toolNames).toContain('list_tickets');
    expect(toolNames).toContain('get_ticket');
    expect(toolNames).toContain('create_ticket');
    expect(toolNames).toContain('update_ticket');
    expect(toolNames).toContain('delete_ticket');
    expect(toolNames).toContain('list_ticket_pipelines');
    expect(toolNames).toContain('update_ticket_status');
    expect(toolNames).toContain('list_locations');
    expect(toolNames).toContain('get_location');
    expect(toolNames).toContain('create_location');
    expect(toolNames).toContain('update_location');
    expect(toolNames).toContain('delete_location');
    expect(toolNames).toContain('list_inventories');
    expect(toolNames).toContain('get_inventory');
    expect(toolNames).toContain('create_inventory');
    expect(toolNames).toContain('update_inventory');
    expect(toolNames).toContain('delete_inventory');
    expect(toolNames).toContain('list_inventory_transactions');
    expect(toolNames).toContain('get_inventory_transaction');
    expect(toolNames).toContain('create_inventory_transaction');
    expect(toolNames).toContain('update_inventory_transaction');
    expect(toolNames).toContain('delete_inventory_transaction');
    expect(toolNames).toContain('list_expenses');
    expect(toolNames).toContain('get_expense');
    expect(toolNames).toContain('upload_expense_attachment');
    expect(toolNames).toContain('start_expense_attachment_upload');
    expect(toolNames).toContain('append_expense_attachment_upload_chunk');
    expect(toolNames).toContain('finish_expense_attachment_upload');
    expect(toolNames).toContain('upload_order_attachment');
    expect(toolNames).toContain('upload_purchase_order_attachment');
    expect(toolNames).toContain('upload_estimate_attachment');
    expect(toolNames).toContain('upload_invoice_attachment');
    expect(toolNames).toContain('upload_import_file');
    expect(toolNames).toContain('import_records');
    expect(toolNames).toContain('get_import_job');
    expect(toolNames).toContain('list_import_jobs');
    expect(toolNames).toContain('cancel_import_job');
    expect(toolNames).toContain('list_integration_channels');
    expect(toolNames).toContain('export_records');
    expect(toolNames).toContain('get_export_job');
    expect(toolNames).toContain('list_export_jobs');
    expect(toolNames).toContain('cancel_export_job');
    expect(toolNames).toContain('create_expense');
    expect(toolNames).toContain('update_expense');
    expect(toolNames).toContain('delete_expense');
    expect(toolNames).toContain('list_employees');
    expect(toolNames).toContain('list_absences');
    expect(toolNames).toContain('get_absence');
    expect(toolNames).toContain('create_absence');
    expect(toolNames).toContain('update_absence');
    expect(toolNames).toContain('delete_absence');
    expect(toolNames).toContain('list_attendance_records');
    expect(toolNames).toContain('get_attendance_record');
    expect(toolNames).toContain('create_attendance_record');
    expect(toolNames).toContain('update_attendance_record');
    expect(toolNames).toContain('delete_attendance_record');
    expect(toolNames).toContain('list_payroll_profiles');
    expect(toolNames).toContain('upsert_payroll_profile');
    expect(toolNames).toContain('list_payroll_runs');
    expect(toolNames).toContain('get_payroll_run');
    expect(toolNames).toContain('download_payroll_payslip_pdf');
    expect(toolNames).toContain('calculate_payroll_run');
    expect(toolNames).toContain('create_payroll_journal_entry');
    expect(toolNames).toContain('approve_payroll_run');
    expect(toolNames).toContain('list_incentives');
    expect(toolNames).toContain('list_incentive_plans');
    expect(toolNames).toContain('list_incentive_company_options');
    expect(toolNames).toContain('create_incentive_plan');
    expect(toolNames).toContain('calculate_incentives');
    expect(toolNames).toContain('approve_incentives');
    expect(toolNames).toContain('generate_incentive_payment_notice');
    expect(toolNames).toContain('list_properties');
    expect(toolNames).toContain('get_property');
    expect(toolNames).toContain('create_property');
    expect(toolNames).toContain('update_property');
    expect(toolNames).toContain('delete_property');
    expect(toolNames).toContain('get_calendar_bootstrap');
    expect(toolNames).toContain('check_calendar_availability');
    expect(toolNames).toContain('create_calendar_attendance');
    expect(toolNames).toContain('cancel_calendar_attendance');
    expect(toolNames).toContain('reschedule_calendar_attendance');
    expect(toolNames).toContain('prospect_companies');
    expect(toolNames).toContain('score_record');
    expect(toolNames).toContain('generate_demo_workspace');
    expect(toolNames).toContain('push_integration_sync');
  });

  it('advertises MCP access as the only OAuth scope on protected tools', () => {
    const tools = selectTools(undefined, 'hosted').map(applyRequiredScopesToSecuritySchemes);
    const listDeals = tools.find((tool) => tool.tool.name === 'list_deals');
    const listInventories = tools.find((tool) => tool.tool.name === 'list_inventories');

    expect(listDeals?.tool.securitySchemes).toEqual([{ type: 'oauth2', scopes: ['mcp:access'] }]);
    expect(listInventories?.tool.securitySchemes).toEqual([{ type: 'oauth2', scopes: ['mcp:access'] }]);
  });

  it('returns unified instructions from the default profile', async () => {
    const instructions = await getInstructions({ toolProfile: 'full' });

    expect(instructions).toContain('execute');
    expect(instructions).toContain('search_docs');
    expect(instructions).toContain('connect_sanka');
    expect(instructions).toContain('auth_status');
    expect(instructions).toContain('list_private_messages');
    expect(instructions).toContain('sync_private_messages');
    expect(instructions).toContain('get_private_message_thread');
    expect(instructions).toContain('reply_private_message_thread');
    expect(instructions).toContain('archive_private_message_thread');
    expect(instructions).toContain('list_workspace_messages');
    expect(instructions).toContain('sync_workspace_messages');
    expect(instructions).toContain('get_workspace_message_thread');
    expect(instructions).toContain('list_associations');
    expect(instructions).toContain('create_association');
    expect(instructions).toContain('delete_association');
    expect(instructions).toContain('list_companies');
    expect(instructions).toContain('get_company');
    expect(instructions).toContain('create_company');
    expect(instructions).toContain('update_company');
    expect(instructions).toContain('delete_company');
    expect(instructions).toContain('get_company_price_table');
    expect(instructions).toContain('update_company_price_table_company');
    expect(instructions).toContain('update_company_price_table_item');
    expect(instructions).toContain('apply_company_price_table_items');
    expect(instructions).toContain('list_contacts');
    expect(instructions).toContain('get_contact');
    expect(instructions).toContain('create_contact');
    expect(instructions).toContain('update_contact');
    expect(instructions).toContain('delete_contact');
    expect(instructions).toContain('list_deals');
    expect(instructions).toContain('get_deal');
    expect(instructions).toContain('create_deal');
    expect(instructions).toContain('update_deal');
    expect(instructions).toContain('delete_deal');
    expect(instructions).toContain('list_deal_pipelines');
    expect(instructions).toContain('capture_pipeline_snapshot');
    expect(instructions).toContain('compare_pipeline_snapshots');
    expect(instructions).toContain('sync_pipeline_snapshot_hubspot_properties');
    expect(instructions).toContain('list_items');
    expect(instructions).toContain('get_item');
    expect(instructions).toContain('create_item');
    expect(instructions).toContain('update_item');
    expect(instructions).toContain('delete_item');
    expect(instructions).toContain('list_orders');
    expect(instructions).toContain('get_order');
    expect(instructions).toContain('create_order');
    expect(instructions).toContain('update_order');
    expect(instructions).toContain('activate_order');
    expect(instructions).toContain('delete_order');
    expect(instructions).toContain('permanent_delete_order');
    expect(instructions).toContain('list_purchase_orders');
    expect(instructions).toContain('get_purchase_order');
    expect(instructions).toContain('download_purchase_order_pdf');
    expect(instructions).toContain('read_binary_download_chunk');
    expect(instructions).toContain('create_purchase_order');
    expect(instructions).toContain('update_purchase_order');
    expect(instructions).toContain('delete_purchase_order');
    expect(instructions).toContain('list_estimates');
    expect(instructions).toContain('get_estimate');
    expect(instructions).toContain('create_estimate');
    expect(instructions).toContain('update_estimate');
    expect(instructions).toContain('delete_estimate');
    expect(instructions).toContain('list_invoices');
    expect(instructions).toContain('list_overdue_invoices');
    expect(instructions).toContain('get_invoice');
    expect(instructions).toContain('send_invoice_email');
    expect(instructions).toContain('Do not render Sanka record numbers as Markdown issue references');
    expect(instructions).toContain('売上請求番号 7');
    expect(instructions).toContain('Order is "受注" and Invoice is "売上請求"');
    expect(instructions).toContain('status=draft should be shown as "下書き"');
    expect(instructions).toContain('For Sanka company cycles');
    expect(instructions).toContain('billing_cycle and payment_cycle are standard company fields');
    expect(instructions).toContain('Do not say a Sanka tool or API call failed unless');
    expect(instructions).toContain('create_invoice');
    expect(instructions).toContain('update_invoice');
    expect(instructions).toContain('activate_invoice');
    expect(instructions).toContain('delete_invoice');
    expect(instructions).toContain('permanent_delete_invoice');
    expect(instructions).toContain('list_subscriptions');
    expect(instructions).toContain('get_subscription');
    expect(instructions).toContain('create_subscription');
    expect(instructions).toContain('update_subscription');
    expect(instructions).toContain('delete_subscription');
    expect(instructions).toContain('list_payments');
    expect(instructions).toContain('get_payment');
    expect(instructions).toContain('list_payment_allocations');
    expect(instructions).toContain('update_payment_allocations');
    expect(instructions).toContain('create_payment');
    expect(instructions).toContain('update_payment');
    expect(instructions).toContain('delete_payment');
    expect(instructions).toContain('list_slips');
    expect(instructions).toContain('get_slip');
    expect(instructions).toContain('create_slip');
    expect(instructions).toContain('update_slip');
    expect(instructions).toContain('delete_slip');
    expect(instructions).toContain('list_bills');
    expect(instructions).toContain('get_bill');
    expect(instructions).toContain('upload_bill_attachment');
    expect(instructions).toContain('create_bill');
    expect(instructions).toContain('update_bill');
    expect(instructions).toContain('delete_bill');
    expect(instructions).toContain('list_disbursements');
    expect(instructions).toContain('get_disbursement');
    expect(instructions).toContain('create_disbursement');
    expect(instructions).toContain('update_disbursement');
    expect(instructions).toContain('delete_disbursement');
    expect(instructions).toContain('list_disbursement_allocations');
    expect(instructions).toContain('create_disbursement_allocation');
    expect(instructions).toContain('update_disbursement_allocation');
    expect(instructions).toContain('delete_disbursement_allocation');
    expect(instructions).toContain('list_tickets');
    expect(instructions).toContain('get_ticket');
    expect(instructions).toContain('create_ticket');
    expect(instructions).toContain('update_ticket');
    expect(instructions).toContain('delete_ticket');
    expect(instructions).toContain('list_ticket_pipelines');
    expect(instructions).toContain('update_ticket_status');
    expect(instructions).toContain('list_locations');
    expect(instructions).toContain('get_location');
    expect(instructions).toContain('create_location');
    expect(instructions).toContain('update_location');
    expect(instructions).toContain('delete_location');
    expect(instructions).toContain('list_inventories');
    expect(instructions).toContain('get_inventory');
    expect(instructions).toContain('create_inventory');
    expect(instructions).toContain('update_inventory');
    expect(instructions).toContain('delete_inventory');
    expect(instructions).toContain('list_inventory_transactions');
    expect(instructions).toContain('get_inventory_transaction');
    expect(instructions).toContain('create_inventory_transaction');
    expect(instructions).toContain('update_inventory_transaction');
    expect(instructions).toContain('delete_inventory_transaction');
    expect(instructions).toContain('list_expenses');
    expect(instructions).toContain('get_expense');
    expect(instructions).toContain('upload_expense_attachment');
    expect(instructions).toContain('start_expense_attachment_upload');
    expect(instructions).toContain('append_expense_attachment_upload_chunk');
    expect(instructions).toContain('finish_expense_attachment_upload');
    expect(instructions).toContain('upload_bill_attachment');
    expect(instructions).toContain('upload_order_attachment');
    expect(instructions).toContain('upload_purchase_order_attachment');
    expect(instructions).toContain('upload_estimate_attachment');
    expect(instructions).toContain('upload_invoice_attachment');
    expect(instructions).toContain('upload_import_file');
    expect(instructions).toContain('import_records');
    expect(instructions).toContain('get_import_job');
    expect(instructions).toContain('list_import_jobs');
    expect(instructions).toContain('cancel_import_job');
    expect(instructions).toContain('list_integration_channels');
    expect(instructions).toContain('export_records');
    expect(instructions).toContain('get_export_job');
    expect(instructions).toContain('list_export_jobs');
    expect(instructions).toContain('cancel_export_job');
    expect(instructions).toContain('create_expense');
    expect(instructions).toContain('update_expense');
    expect(instructions).toContain('delete_expense');
    expect(instructions).toContain('list_employees');
    expect(instructions).toContain('list_absences');
    expect(instructions).toContain('create_absence');
    expect(instructions).toContain('list_attendance_records');
    expect(instructions).toContain('create_attendance_record');
    expect(instructions).toContain('list_payroll_profiles');
    expect(instructions).toContain('download_payroll_payslip_pdf');
    expect(instructions).toContain('calculate_payroll_run');
    expect(instructions).toContain('create_payroll_journal_entry');
    expect(instructions).toContain('approve_payroll_run');
    expect(instructions).toContain('list_incentives');
    expect(instructions).toContain('list_incentive_plans');
    expect(instructions).toContain('list_incentive_company_options');
    expect(instructions).toContain('create_incentive_plan');
    expect(instructions).toContain('calculate_incentives');
    expect(instructions).toContain('approve_incentives');
    expect(instructions).toContain('generate_incentive_payment_notice');
    expect(instructions).toContain('list_properties');
    expect(instructions).toContain('get_property');
    expect(instructions).toContain('create_property');
    expect(instructions).toContain('update_property');
    expect(instructions).toContain('delete_property');
    expect(instructions).toContain('get_calendar_bootstrap');
    expect(instructions).toContain('check_calendar_availability');
    expect(instructions).toContain('create_calendar_attendance');
    expect(instructions).toContain('cancel_calendar_attendance');
    expect(instructions).toContain('reschedule_calendar_attendance');
    expect(instructions).toContain('prospect_companies');
    expect(instructions).toContain('score_record');
    expect(instructions).toContain('structuredContent.required_user_facing_reply');
    expect(instructions).toContain('generate_demo_workspace');
    expect(instructions).toContain('push_integration_sync');
    expect(instructions).toContain('prefer the plugin-attached Sanka namespace');
    expect(instructions).toContain('mcp__sanka_key__*');
    expect(instructions).toContain('売上請求番号 7');
    expect(instructions).toContain('Order is "受注" and Invoice is "売上請求"');
    expect(instructions).toContain('status=draft should be shown as "下書き"');
    expect(instructions).toContain('For Sanka company cycles');
    expect(instructions).toContain('billing_cycle and payment_cycle are standard company fields');
    expect(instructions).toContain('Only use download_estimate_pdf when the user explicitly asks');
  });

  it('returns hosted instructions without generic docs/code tools', async () => {
    const instructions = await getInstructions({ toolProfile: 'hosted' });

    expect(instructions).not.toContain('execute');
    expect(instructions).not.toContain('search_docs');
    expect(instructions).toContain('connect_sanka');
    expect(instructions).toContain('auth_status');
    expect(instructions).toContain('list_private_messages');
    expect(instructions).toContain('sync_private_messages');
    expect(instructions).toContain('get_private_message_thread');
    expect(instructions).toContain('reply_private_message_thread');
    expect(instructions).toContain('archive_private_message_thread');
    expect(instructions).toContain('list_workspace_messages');
    expect(instructions).toContain('sync_workspace_messages');
    expect(instructions).toContain('get_workspace_message_thread');
    expect(instructions).toContain('list_associations');
    expect(instructions).toContain('create_association');
    expect(instructions).toContain('delete_association');
    expect(instructions).toContain('list_companies');
    expect(instructions).toContain('get_company');
    expect(instructions).toContain('create_company');
    expect(instructions).toContain('update_company');
    expect(instructions).toContain('delete_company');
    expect(instructions).toContain('get_company_price_table');
    expect(instructions).toContain('update_company_price_table_company');
    expect(instructions).toContain('update_company_price_table_item');
    expect(instructions).toContain('apply_company_price_table_items');
    expect(instructions).toContain('list_contacts');
    expect(instructions).toContain('get_contact');
    expect(instructions).toContain('create_contact');
    expect(instructions).toContain('update_contact');
    expect(instructions).toContain('delete_contact');
    expect(instructions).toContain('list_deals');
    expect(instructions).toContain('get_deal');
    expect(instructions).toContain('create_deal');
    expect(instructions).toContain('update_deal');
    expect(instructions).toContain('delete_deal');
    expect(instructions).toContain('list_deal_pipelines');
    expect(instructions).toContain('capture_pipeline_snapshot');
    expect(instructions).toContain('compare_pipeline_snapshots');
    expect(instructions).toContain('sync_pipeline_snapshot_hubspot_properties');
    expect(instructions).toContain('list_items');
    expect(instructions).toContain('get_item');
    expect(instructions).toContain('create_item');
    expect(instructions).toContain('update_item');
    expect(instructions).toContain('delete_item');
    expect(instructions).toContain('list_orders');
    expect(instructions).toContain('get_order');
    expect(instructions).toContain('create_order');
    expect(instructions).toContain('update_order');
    expect(instructions).toContain('activate_order');
    expect(instructions).toContain('delete_order');
    expect(instructions).toContain('permanent_delete_order');
    expect(instructions).toContain('list_purchase_orders');
    expect(instructions).toContain('get_purchase_order');
    expect(instructions).toContain('download_purchase_order_pdf');
    expect(instructions).toContain('read_binary_download_chunk');
    expect(instructions).toContain('create_purchase_order');
    expect(instructions).toContain('update_purchase_order');
    expect(instructions).toContain('delete_purchase_order');
    expect(instructions).toContain('list_estimates');
    expect(instructions).toContain('get_estimate');
    expect(instructions).toContain('create_estimate');
    expect(instructions).toContain('update_estimate');
    expect(instructions).toContain('delete_estimate');
    expect(instructions).toContain('list_invoices');
    expect(instructions).toContain('list_overdue_invoices');
    expect(instructions).toContain('get_invoice');
    expect(instructions).toContain('send_invoice_email');
    expect(instructions).toContain('create_invoice');
    expect(instructions).toContain('update_invoice');
    expect(instructions).toContain('activate_invoice');
    expect(instructions).toContain('delete_invoice');
    expect(instructions).toContain('permanent_delete_invoice');
    expect(instructions).toContain('list_subscriptions');
    expect(instructions).toContain('get_subscription');
    expect(instructions).toContain('create_subscription');
    expect(instructions).toContain('update_subscription');
    expect(instructions).toContain('delete_subscription');
    expect(instructions).toContain('list_payments');
    expect(instructions).toContain('get_payment');
    expect(instructions).toContain('list_payment_allocations');
    expect(instructions).toContain('update_payment_allocations');
    expect(instructions).toContain('create_payment');
    expect(instructions).toContain('update_payment');
    expect(instructions).toContain('delete_payment');
    expect(instructions).toContain('list_slips');
    expect(instructions).toContain('get_slip');
    expect(instructions).toContain('create_slip');
    expect(instructions).toContain('update_slip');
    expect(instructions).toContain('delete_slip');
    expect(instructions).toContain('list_bills');
    expect(instructions).toContain('get_bill');
    expect(instructions).toContain('upload_bill_attachment');
    expect(instructions).toContain('create_bill');
    expect(instructions).toContain('update_bill');
    expect(instructions).toContain('delete_bill');
    expect(instructions).toContain('list_disbursements');
    expect(instructions).toContain('get_disbursement');
    expect(instructions).toContain('create_disbursement');
    expect(instructions).toContain('update_disbursement');
    expect(instructions).toContain('delete_disbursement');
    expect(instructions).toContain('list_disbursement_allocations');
    expect(instructions).toContain('create_disbursement_allocation');
    expect(instructions).toContain('update_disbursement_allocation');
    expect(instructions).toContain('delete_disbursement_allocation');
    expect(instructions).toContain('list_tickets');
    expect(instructions).toContain('get_ticket');
    expect(instructions).toContain('create_ticket');
    expect(instructions).toContain('update_ticket');
    expect(instructions).toContain('delete_ticket');
    expect(instructions).toContain('list_ticket_pipelines');
    expect(instructions).toContain('update_ticket_status');
    expect(instructions).toContain('list_locations');
    expect(instructions).toContain('get_location');
    expect(instructions).toContain('create_location');
    expect(instructions).toContain('update_location');
    expect(instructions).toContain('delete_location');
    expect(instructions).toContain('list_inventories');
    expect(instructions).toContain('get_inventory');
    expect(instructions).toContain('create_inventory');
    expect(instructions).toContain('update_inventory');
    expect(instructions).toContain('delete_inventory');
    expect(instructions).toContain('list_inventory_transactions');
    expect(instructions).toContain('get_inventory_transaction');
    expect(instructions).toContain('create_inventory_transaction');
    expect(instructions).toContain('update_inventory_transaction');
    expect(instructions).toContain('delete_inventory_transaction');
    expect(instructions).toContain('list_expenses');
    expect(instructions).toContain('get_expense');
    expect(instructions).toContain('upload_expense_attachment');
    expect(instructions).toContain('start_expense_attachment_upload');
    expect(instructions).toContain('append_expense_attachment_upload_chunk');
    expect(instructions).toContain('finish_expense_attachment_upload');
    expect(instructions).toContain('upload_bill_attachment');
    expect(instructions).toContain('upload_order_attachment');
    expect(instructions).toContain('upload_purchase_order_attachment');
    expect(instructions).toContain('upload_estimate_attachment');
    expect(instructions).toContain('upload_invoice_attachment');
    expect(instructions).toContain('upload_import_file');
    expect(instructions).toContain('import_records');
    expect(instructions).toContain('get_import_job');
    expect(instructions).toContain('list_import_jobs');
    expect(instructions).toContain('cancel_import_job');
    expect(instructions).toContain('list_integration_channels');
    expect(instructions).toContain('export_records');
    expect(instructions).toContain('get_export_job');
    expect(instructions).toContain('list_export_jobs');
    expect(instructions).toContain('cancel_export_job');
    expect(instructions).toContain('create_expense');
    expect(instructions).toContain('update_expense');
    expect(instructions).toContain('delete_expense');
    expect(instructions).toContain('list_employees');
    expect(instructions).toContain('list_absences');
    expect(instructions).toContain('create_absence');
    expect(instructions).toContain('list_attendance_records');
    expect(instructions).toContain('create_attendance_record');
    expect(instructions).toContain('list_payroll_profiles');
    expect(instructions).toContain('download_payroll_payslip_pdf');
    expect(instructions).toContain('calculate_payroll_run');
    expect(instructions).toContain('create_payroll_journal_entry');
    expect(instructions).toContain('approve_payroll_run');
    expect(instructions).toContain('list_incentives');
    expect(instructions).toContain('list_incentive_plans');
    expect(instructions).toContain('list_incentive_company_options');
    expect(instructions).toContain('create_incentive_plan');
    expect(instructions).toContain('calculate_incentives');
    expect(instructions).toContain('approve_incentives');
    expect(instructions).toContain('generate_incentive_payment_notice');
    expect(instructions).toContain('list_properties');
    expect(instructions).toContain('get_property');
    expect(instructions).toContain('create_property');
    expect(instructions).toContain('update_property');
    expect(instructions).toContain('delete_property');
    expect(instructions).toContain('get_calendar_bootstrap');
    expect(instructions).toContain('check_calendar_availability');
    expect(instructions).toContain('create_calendar_attendance');
    expect(instructions).toContain('cancel_calendar_attendance');
    expect(instructions).toContain('reschedule_calendar_attendance');
    expect(instructions).toContain('prospect_companies');
    expect(instructions).toContain('score_record');
    expect(instructions).toContain('structuredContent.required_user_facing_reply');
    expect(instructions).toContain('generate_demo_workspace');
    expect(instructions).toContain('push_integration_sync');
    expect(instructions).toContain('prefer the plugin-attached Sanka namespace');
    expect(instructions).toContain('mcp__sanka_key__*');
    expect(instructions).toContain('Only use download_estimate_pdf when the user explicitly asks');
  });
});
